README.md

Document necessary environment variables for macOS for `go get` to succeed.
Without these, `go get` will fail, even if `openssl` is installed:
```
$ go get -u github.com/pions/webrtc
In file included from ../../pions/webrtc/internal/dtls/dtls.go:10:
./dtls.h:4:10: fatal error: 'openssl/bio.h' file not found
#include <openssl/bio.h>
^~~~~~~~~~~~~~~
1 error generated.
```

Update README for macOS

---

examples/gstreamer-send/README.md

Tiny PR to document how I got gstreamer-send working in Windows. The SessionDescription gets cut off to 4096 bytes when pasting in the terminal window.

gstreamer-send: document running in Windows.

---

examples/gstreamer-receive/main.go
examples/gstreamer-send/main.go
examples/save-to-disk/main.go
rtcconfiguration.go
rtcconfiguration_test.go
rtcpeerconnection.go

This PR lays the foundation to get a `RTCConfiguration` object into the library without compromising local/ remote functionality.

add RTCConfiguration and RTCPeerConnection constructor

---

examples/gstreamer-receive/main.go
examples/gstreamer-send/main.go
examples/save-to-disk/main.go
examples/stun/main.go
rtcconfiguration.go
rtcconfiguration_test.go
rtcpeerconnection.go

this PR adds support for modern STUN, as specified in [RFC 5389](https://tools.ietf.org/html/rfc5389). Once merged this will close #18.
Missing is stuns support, as well as automatic end 2 end tests to ensure that this functionality does not break. I'll be working on adding those afterwards.

basic STUN support

---

rtcsdptype.go
rtcsessiondescription.go
rtcsessiondescription_test.go

Allow json (un)marshalling of a SessionDescription for easier exchange, especially with JavaScript clients.
cc #39

SessionDescription: Allow json (un)marshalling.

---

rtcpeerconnection.go

Nodejs fails to apply an sdp answer if it has a bundle attribute without any mids.

nodejs bundle

---

.github/lint-commit-message.sh
.travis.yml

Implement commit message linting that asserts the following rules
* Separate subject from body with a blank line
* Limit the subject line to 50 characters
* Capitalize the subject line
* Do not end the subject line with a period
* Wrap the body at 72 characters
* Must include 'Relates to #' or 'Resolves #' on its own line
Resolves #122

Add commit message linting

---

.github/lint-disallowed-functions-in-library.sh

The lint-disallowed-functions-in-library.sh lint is
stopping people from  using helpful functions in tests, raise
the restriction in files that match _test.go
Resolves #127

Allow panics in test files

---

rtcconfiguration.go
rtcconfiguration_test.go

Tiny PR that only adds one function that is used in later PRs for ease of ice server parsing.
Relates to #83

Add getIceServers to support easy server parsing

---

.travis.yml

We don't write unit tests for examples, exclude them from coveralls
Resolves #147

Remove examples directory before running tests

---

CONTRIBUTING.md
DESIGN.md
README.md
examples/README.md

Goals:
- Link to the examples from the main README.
- Draw attention to the things that matter most.
- Liven the docs up a bit but keep it minimal.
Possible future improvements:
- Replace the entire 'install' section with `go get github.com/pions/webrtc`.
- Remove the roadmap section when things stabilize.
- Maybe create a pions/awesome-webrtc to feature other peoples projects.

Docs: Improve docs

---

examples/data-channels/main.go
examples/gstreamer-receive/main.go
examples/pion-to-pion/offer/main.go
examples/save-to-disk/main.go
rtcpeerconnection.go

Methods that were marked as deprecated weren't properly handled. There
was a mix of old+new ones supported which caused broken behavior.
SDP creation didn't add SCTP to Offer
Resolves #156

Fix deprecation cutover, and bad SDP creation

---

pkg/ice/agent.go
pkg/ice/candidate.go

- Periodically send a keep-alive Binding Indication.
- Downgrade connection state to disconnected after timeout.
Resolves #163 
Potential future improvements:
- Better connection management by pinging the candidate with binding requests (inspired by chrome implementation).
- Avoid keep-alive in case of data packets (gave up on this one due to callback/locking hell).
- Implement the Completed and Failed connection states.

ICE: Implement keep-alive

---

examples/data-channels-create/main.go
pkg/ice/agent.go

- Avoid USE-CANDIDATE attribute in binding requests by the controlled agent.
- Don't respond to success responses in handleInboundControlled.
- Re-send a binding with USE-CANDIDATE when the controlling agent receives a binding.
Resolves #164

ICE: Improve nomination

---

internal/network/manager.go

Handle silently ChannelAck for now.
Relates to #167

DataChannels: Silently ignore ChannelAck

---

README.md
examples/janus-gateway/README.md
examples/janus-gateway/streaming/main.go
rtcpeerconnection.go

This adds an example of how to use pion-WebRTC with the streaming
plugin. This isn't production ready until #175 is resolved, but is
enough to start adding rough code/debugging around.
Resolves #74
Co-authored-by: Sean DuBois <sean@siobud.com>

Add examples of using pion-WebRTC with Janus

---

pkg/rtp/codecs/opus_packet.go

Later operations are done in place (like SRTP), and
we don't want to put the burden on the user for copying.
Resolves #183

RTP packetization should copy payload

---

pkg/ice/agent.go

This value is incorrect if agent is controlling, instead of fixing
remove instead. We don't need this value in the keepalive.
Resolves #187

Remove IceControlled Attr from ICE keepalive

---

rtcpeerconnection.go

Multiple calls to RTCPeerConnection.Close would cause a segfault in
OpenSSL. Closing the NetworkManager was incorrectly placed after
the `isClosed` early return.
This moves the networkManager.Close() after that early return
Resolves #109

Fix RTCPeerConnection.Close segfault

---

README.md
examples/pion-to-pion/README.md
examples/pion-to-pion/answer/Dockerfile
examples/pion-to-pion/docker-compose.yml
examples/pion-to-pion/offer/Dockerfile

Hello, 
I think, that docker-compose can help to start the example. If you don't like a docker, just Decline this PR.

Adding Docker-compose for pion-to-pion example

---

README.md
internal/dtls/dtls.c
internal/dtls/dtls.go
internal/dtls/dtls.h

Implement dtls_tlscfg_fingerprint in Go.
Resolves #132

GENERATE CERTIFICATE FINGERPRINT IN GO

---

.travis.yml

golang-ci is broken against master, golang-ci doesn't support master so
latest and (latest - 2) is good enough for now testing wise
Resolves #211

Run golang-ci against 1.9/1.11 only

---

README.md
media.go
pkg/rtp/packetizer.go
rtcpeerconnection.go
rtcpeerconnection_test.go

Resolves #212
Support forwarding packets from existing RTP streams. Adds
the following new methods to RTCPeerConnection:
* NewRawRTPTrack() -- expects a non-zero SSRC and accepts
a stream of *rtp.Packet from an existing RTP stream
* NewRTCSampleTrack() -- generates an SSRC and accepts
a stream of media.RTCSample
Deprecates NewRTCTrack() in favor of NewRTCSampleTrack().
Exposes a new RawRTP channel on *RTCTrack instances which
accepts *rtp.Packet.

Allow Raw RTP input to RTCTrack

---

pkg/ice/agent.go
rtcpeerconnection.go

Resolves #220
Adds remote candidates to agent asynchronously. Changes remote
candidates slice to a map keyed by candidate string in order to
avoid duplicate entries.

Simple Trickle-ICE support

---

examples/data-channels-create/main.go
examples/data-channels/main.go
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/main.go
examples/janus-gateway/streaming/main.go
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go
examples/save-to-disk/main.go
examples/sfu/main.go
media.go
rtcdatachannel.go
rtcdatachannel_test.go
rtcpeerconnection.go
rtcpeerconnection_test.go

Resolves #218
Change Event Callback APIs to setter functions which take care of
locking so that users don't need to know about or remember
to do this.

Safer Event Callbacks

---

examples/examples.go
examples/gstreamer-send/main.go
examples/sfu/main.go

Move from NewRTCTrack -> NewRTCSampleTrack and a few other
simple cases
Resolves #238

Update examples to use non-deprecated APIs

---

.gitignore
.travis.yml

We are currently only uploading the coverage for the main package, so
our coverage appears much lower then it really is. This updates our
tooling to properly cover every package
Resolves #240

Fix multi-package coverage generation

---

pkg/rtcp/fuzz.go

This will help find crashers and security issues lurking in our
parser code, and parser edge cases we haven't thought of yet.
Visit https://github.com/dvyukov/go-fuzz for more information
Relates to #251

Add go-fuzzer support to RTCP package

---

pkg/ice/agent.go
pkg/ice/candidate.go
pkg/ice/transport_test.go

Rebase of @mjmac's #260 since it was reverted.
Found a couple of minor races -- just use mutexes to ensure
synchronized access.
Relates to #110

Fix races in SCTP/ICE

---

internal/sdp/ice.go
pkg/ice/networktype.go
pkg/ice/networktype_test.go
rtcpeerconnection.go

Before we would fail to parse networkType if it was upcased. Also return
errors when networkType is unknown
Resolves #289

Ignore case when parsing candidate networkType

---

examples/util/gstreamer-src/gst.go
mediaengine.go

* allow GST examples to use g722
* Assume G722 is mono -- that's what chrome likes,
and i don't know if anyone's doing stereo g722 anyway
Relates to #283

Tweak g722 support code (so that it actually works...)

---

internal/sdp/jsep.go
internal/sdp/marshal_test.go
internal/sdp/media_description.go
internal/sdp/unmarshal.go
rtcpeerconnection.go

We don't mirror the format in the answer as described [here](https://blog.mozilla.org/webrtc/how-to-avoid-data-channel-breaking/) but just fixing the parsing does fix Firefox support.
Resolves #208

SDP: Change Media Descriptions fmt to string

---

internal/sdp/jsep.go

Make sure that payload types are correctly rendered
in 'm=' lines. the 'string' constructor renders the
ordinal (ascii representation) when given a uint8,
not a decimal integer
Relates to #299

Fix a small bug in SDP rendering

---

internal/srtp/context.go
internal/srtp/srtp.go
internal/srtp/srtp_test.go

Auth tag verification before would hash including the old auth tag, now
we remove the old tag before generating the hash
Resolves #270

Re-enable SRTP Auth tag verification

---

internal/network/manager.go
pkg/ice/agent.go
pkg/ice/transport_test.go
rtcconfiguration.go
rtcpeerconnection.go
settingengine.go

This allows primitive (non-stateful) firewalls to have less wide-open configuration, while still maintaining some chance of getting UDP packets out...

Allow local ephemeral port range to be limited

---

examples/data-channels-detach-create/README.md
examples/data-channels-detach-create/main.go
examples/data-channels-detach/README.md
examples/data-channels-detach/main.go
rtcdatachannel.go
settingengine.go

This is the initial experiment towards providing direct access to the data channel as described in #277. Once detached the `io.ReadWriter` API feels very familiar. In addition, this seems really powerful for more networking oriented applications. E.g.: a lot of silly glue logic could be removed from `pions/dcnet`.
If you want to build this branch right now, you have to manually move the `sctp` and `datachannel` package under the pions root.
TODO:
- `OnOpen` seems like a good candidate but it is asynchronous ATM.
- Signal early that you want to detach somehow (settings manager?) and have a method to get the `datachannel.DataChannel` object once it exists.
- Add an OnDetach callback. However, this would also suffer from #305. Preferably we won't have to solve this twice.

Detach: Expose data channel networking

---

pkg/ice/agent.go
pkg/ice/candidate.go
pkg/ice/candidatepair.go
pkg/ice/logging.go
pkg/logging/leveled.go
pkg/logging/logging_test.go
pkg/logging/scoped.go
rtcpeerconnection.go

Not sure about this yet, going to live with it for a bit locally to see how it feels. Updated the Ice agent with debug logging as an example.

Add Leveled/Scoped logging facility

---

README.md
pkg/ice/agent.go

The `lastSent` value on a remote component of selected-pair never gets updated, which was the reason why LastSent() returned a large duration, causing the keepalive packet sent every 2 seconds.

Fix keepalive transmission interval mentioned in issue #331

---

rtcicetransport.go
rtcpeerconnection.go

Resolves #349
Drop the write lock in RTCIceTransport.Start() so that
candidates can be added to the agent. Once the connection
is established, reacquire the lock to safely set up the mux.
Also fixes a couple of other thread safety issues found in
local testing.

Fix deadlock with trickle-ICE candidates

---

rtciceprotocol.go
rtciceprotocol_test.go

Before we would fail to parse RTCIceProtocol if it was upcased.
Relates to #289

Ignore case when parsing RTCIceProtocol

---

README.md
pkg/ice/agent.go
pkg/ice/candidate.go

This way, we update lastReceived properly, not just for STUN messages.
We are using lastReceived to check for a connection timeout (https://github.com/pions/webrtc/blob/master/pkg/ice/agent.go#L442) but the problem was we were not updating lastReceived for non STUN messages

Agent handles any inbound package (as opposed to STUN only)

---

errors.go
rtcpeerconnection.go

Return proper error and prevent nil pointer dereference

Return error if AddIceCandidate is called but no remote description is set

---

rtcpeerconnection.go

References #372
The test for nil remote description is backwards, resulting
in errors being returned when there is a remote description
set.

Fix inverted logic for AddIceCandidate check

---

pkg/quic/internal/wrapper/quic.go
rtcquictransport_test.go

QUIC still leaks, but not causing other tests to flake

Bump dependencies and enable QUIC tests

---

examples/util/gstreamer-sink/gst.c
examples/util/gstreamer-src/gst.c

When an element is selected by `gst_bin_get_by_name` we need to make sure that we also `gst_object_unref` it.
Fixes #394

Fixed minor pipeline/element memory leak in examples/util

---

examples/util/gstreamer-src/gst.go

**Situation**: Create multiple gstreamer pipelines but don't service one (or more) of their output channels.
**Expected Result**: The non-serviced pipeline blocks, but the other pipelines continue to send data.
**Actual result**: All pipelines block.
Note, this doesn't make `gstreamer-src` perfect, but its a mild improvement for some use cases with no drawbacks that are evident to me. Feedback welcome.

Gstreamer: avoid lock contention with pipeline

---

api.go
examples/data-channels-close/main.go
examples/data-channels-create/main.go
examples/data-channels-detach-create/main.go
examples/data-channels-detach/main.go
examples/data-channels/main.go
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/main.go
examples/janus-gateway/streaming/main.go
examples/janus-gateway/video-room/main.go
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go
examples/save-to-disk/main.go
examples/sfu/main.go
rtcpeerconnection.go
rtcpeerconnection_test.go

This deviates from the WebRTC spec, so we need to fix it. This is a
massively breaking change, so we need to figure out the best way to help
users with this.
I also renamed our RTCPeerConnection constructor. The hope is that
people will refer to the examples/backlog and see what changed.
Resolves #309
-----
I added all the devs as a heads up, if you think there is a better way we can handle this I am all ears!

Stop Create(Offer/Answer) from setting localDesc

---

examples/gstreamer-receive/main.go
examples/util/gstreamer-sink/gst.go

The Glib loop is run in the main thread (in the OS point of view)
This is a simpler solution than [Russ Cox's solution](https://groups.google.com/forum/#!msg/golang-nuts/IiWZ2hUuLDA/SNKYYZBelsYJ) because of the simpler nature of gstreamer-receive.

Gstreamer-receive reserves main thread for Glib loop

---

examples/gstreamer-receive/main.go
examples/janus-gateway/streaming/main.go
examples/janus-gateway/video-room/main.go
examples/save-to-disk/main.go
examples/sfu/main.go
go.mod
go.sum
icecandidate.go
icecandidate_test.go
iceserver_test.go
mediaengine.go
mediaengine_test.go
oauthcredential.go
peerconnection.go
peerconnection_media_test.go
peerconnection_test.go
rtpreceiver.go
rtpsender.go
sdptype_test.go
sessiondescription.go
sessiondescription_test.go
track.go

Change capitalization to be consistent with other uses in the project, and to match the Go convention of capitalizing initialisms:
https://github.com/golang/go/wiki/CodeReviewComments#initialisms
Relates to #417

API: Make initialisms more consistent

---

icecandidateinit.go
icecandidateinit_test.go
peerconnection.go

API: Use ICECandidateInit in AddICECandidate

---

api.go
examples/data-channels-detach-create/main.go
examples/data-channels-detach/main.go

Limit global API to the basics needed to construct a PeerConnection.

Remove global API for settings engine

---

datachannel_test.go
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/main.go
examples/internal/gstreamer-src/gst.go
examples/janus-gateway/streaming/main.go
examples/janus-gateway/video-room/main.go
examples/save-to-disk/main.go
examples/sfu/main.go
lossy_stream.go
peerconnection.go
peerconnection_media_test.go
peerconnection_test.go
pkg/ice/ice_test.go
rtpreceiver.go
rtpsender.go
rtptranceiver.go
track.go

The Track API has been rewritten to remove Channels from the public API. This was done because we ran into the following issues.
* Use tight loops to read/write from Channels to exchange RTP/RTCP packets is more expensive then I realized
* We were unable to return errors when reading/write RTP or RTCP
* We were unable to close channels (or risk causing a panic if the user writes to them)
We also gained some unforeseen benefits moving to the new API.
* A Track can be added to multiple `PeerConnections` now. The most common use-case so far has been building SFUs, and this feature will reduce complexity for everyone. This also more closely follows the browser implementation of WebRTC.
```
peerConnection.OnTrack(func(track *webrtc.Track) {
})
```
```
peerConnection.OnTrack(func(track …
```

Move to new Track API

---

README.md
peerconnection.go
rtpreceiveparameters.go
rtpreceiver.go
rtpsender.go
rtpsendparameters.go

It's not possible to use a RTPReceiver without it.

Expose Encodings variable for ORTC

---

peerconnection.go

A PeerConnection is now able to mux multiple tracks. by removing this
resriction two tracks with the same ID are delivered to the client
muxed as one MediaStream.
Resolves #440

Allow multiple Tracks with the same ID

---

peerconnection.go

CreateAnswer currently omits any m= lines from the offer that contain
unsupported codecs. The jsep spec says that unsupported lines in the
offer need to be explicitly rejected by setting the port number to 0.
Related to #449

Explicitly reject unsupported m= lines

---

README.md
examples/janus-gateway/README.md

Documented how to build the janus-gateway example on OSX.

Docs: Build Janus example on OSX

---

examples/save-to-disk/main.go
mediaengine.go

The spec states that, to be packaged in RTP, Opus needs to have exactly 2 channels. If we remove that argument from the codec creation process, we're removing one place that's easy to get wrong.

Don't allow RTP codecs that violate RFC7587

---

examples/gstreamer-send-offer/README.md
examples/gstreamer-send-offer/main.go
examples/internal/signal/http.go
examples/sfu/main.go

Combine `gstreamer-receive` and `gstreamer-send-offer` so people can
easily see how to transport audio/video without using their browser.
This moves the HTTP endpoint out of `examples/sfu` so it can be used in
multiple examples
Resolves #472

Provide easy example of video without browser

---

examples/janus-gateway/README.md
examples/janus-gateway/video-room/main.go

Example wasn't sending keep-alives, causing Janus to eventually
end the session even if we weren't done sending

Update janus-gateway/video-room with keepalive

---

internal/mux/mux.go
peerconnection.go
peerconnection_media_test.go
peerconnection_test.go

DTLS shutdown deadlocks if Close is called before startup completes,
because the DTLS connection hasn't finished yet we don't have handles
to close anything.
This updates DTLS to follow how SCTP is shutdown, by shutting down the
nextConn (ICE in this case) we can shutdown the subsystem. By closing
ICE first, DTLS (and then SCTP) close properly no matter what state
they are in.

Fix deadlock in DTLS shutdown

---

examples/save-to-disk/README.md
examples/save-to-disk/main.go
pkg/media/ivfwriter/ivfwriter.go

Relates to #471
The framecount of the IVF header is now updated when we call the `Close` method.
I'm considering passing the `width` and `height` fields as parameters to `New()` method, and keeping a constan 30 framerate. Any thoughts on this?

Hardcoded header in IVFWriter

---

datachannel.go

Now it uses write lock in this PR.
No regression in unit tests, race detection nor golangci-lint in my local run.
I noticed the was a race (reported as #509), not caused by this modification.
Resolves #505

[WIP] Fix race in DataChannel.open()

---

datachannel.go
datachannel_go_test.go
peerconnection.go
sctptransport.go

As discussed in slack, all DataChannel public props are converted to methods to avoid race conditions.
Resolves #505

Change public DataChannel props to methods

---

README.md

The new [wiki page](https://github.com/pions/webrtc/wiki/WebAssembly-Development-and-Testing) provides some additional context about how to develop on the Wasm bindings and run the tests.

Add link to Wasm wiki page in README

---

mediaengine.go
peerconnection.go
rtcpfeedback.go

These are optional RTCP packets that will be sent if enabled in the
offer/answer. They currently all default to disabled because
pions/webrtc has no built-in support to handle these packets. We can
change the default values in the future but until then, they use too
much bandwidth.
The API may be controversial because I'm extending the WebRTC spec. I
don't think that there's any issue providing a superset of the API. We
already do it today by adding methods to RTPSender, and it makes the
interface a lot nicer.

Add feedback support to SDP generation.

---

README.md
examples/sfu-ws/broadcast_data.go
examples/sfu-ws/room.go
examples/sfu-ws/sfu.html

I'm doing with sfu-ws and trying to improve the example with data-channel broadcasting.
Relates to #534

Examples: extend sfu-ws with data-channel broadcasting

---

api.go
certificate.go
configuration_js.go
datachannel_js.go
examples/data-channels/jsfiddle/main.go
icegatherer.go
iceserver.go
iceserver_js.go
iceserver_test.go
js_utils.go
mediaengine.go
mediaengine_test.go
peerconnection_go_test.go
peerconnection_js.go
peerconnection_js_test.go
peerconnection_test.go
settingengine.go
settingengine_test.go

This includes a few small and closely related changes:
1. All occurrences of the build tag `+build js` have been changed to the
more precise `+build js,wasm`. This will exclude the files from being
included by third-party compilers like GopherJS, with which they are
incompatible.
2. Some files which are incompatible with JavaScript/Wasm now have the
correct build tag (`+build -js`) so they will be excluded from Wasm
builds.
3. Some configuration options which are incompatible with
JavaScript/Wasm (or at least the current bindings) will now no longer
appear in Wasm builds. This meant creating new files with new struct
definitions and the appropriate build tags.
Fixes #515

Improve build tags for Wasm

---

test-wasm/go_js_wasm_exec

Adds a Node.js version check to the go_js_wasm_exec shell script, which is required for running the tests for the JavaScript/Wasm bindings.
Fixes #529.

Check Node.js version in go_js_wasm_exec script

---

dtlstransport.go
go.mod
go.sum
peerconnection.go
peerconnection_media_test.go
rtpsender.go

Writing to a Track shouldn't return errors for an individual
RTPSender. This filters ErrNoCandidatePairs from being returned
and instead just returns nil
Resolves #523
----
@thetooth mind checking out this PR and seeing if it works for you? thanks!

Don't notify users via Track of ICE errors

---

examples/janus-gateway/streaming/main.go
examples/save-to-disk/main.go
pkg/media/ivfwriter/ivfwriter.go
pkg/media/ivfwriter/ivfwriter_test.go
pkg/media/media.go
pkg/media/opuswriter/opuswriter.go
pkg/media/opuswriter/opuswriter_test.go

Makes the name consistent with webrtc's WriteRTP and makes webrtc.Track a Writer.
Fixes #556

Rename media.Writer AddPacket -> WriteRTP

---

peerconnection.go

Properly use locks when accessing Transceivers
Resolves #431

Don't iterate Transceivers without lock

---

api_js.go
datachannel_js.go
datachannel_js_detach.go
examples/data-channels-detach/jsfiddle/demo.css
examples/data-channels-detach/jsfiddle/demo.html
examples/data-channels-detach/jsfiddle/main.go
examples/examples.json
peerconnection_js.go
settingengine_js.go

Support for Detach when targeting JS/WASM. The goal is to enable the same idiomatic API in both Native and WASM. This is a POC of the shim to turn the JS OnMessage Callback into the ReadWriteCloser interface used by the DataChannel.Detach. I tried to avoid leaking JS code into pions/datachannel by introducing an interface. Therefore this depends on pions/datachannel#11.

WASM Detach

---

pkg/media/rtpdump/reader.go
pkg/media/rtpdump/reader_test.go
pkg/media/rtpdump/rtpdump.go
pkg/media/rtpdump/rtpdump_test.go
pkg/media/rtpdump/writer.go
pkg/media/rtpdump/writer_test.go

RTPDump is a widely-implemented file format for saving RTP packet dumps
without the overhead of UDP and IP headers found in pcap dumps. libWebRTC,
Wireshark, and RTPTools all have an implementation.
For more information see https://www.cs.columbia.edu/irt/software/rtptools
This commit enables users to save RTP media streams to a file and play them
back later.
Relates to #522

Implement RTPDump Reader/Writer

---

examples/gstreamer-receive/README.md
examples/gstreamer-receive/jsfiddle/demo.html
examples/gstreamer-receive/jsfiddle/demo.js
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/README.md
examples/gstreamer-send/jsfiddle/demo.js
examples/gstreamer-send/main.go
examples/internal/gstreamer-src/gst.go
examples/janus-gateway/streaming/main.go
examples/janus-gateway/video-room/main.go
examples/save-to-disk/main.go
examples/sfu-minimal/README.md
examples/sfu-minimal/jsfiddle/demo.js
examples/sfu-minimal/main.go
examples/sfu-ws/room.go
examples/sfu-ws/sfu.html
mediaengine.go
peerconnection.go
peerconnection_media_test.go
rtptransceiver.go
rtptransceiverinit.go
track.go

This commit does cause some breaking changes. This API change means we
can no longer support an arbitrary number of receivers. For every track
you want to receive you MUST call PeerConnection.AddTransceiver
We do now support sending an multiple audio/video feeds. You can see
this behavior via gstreamer-receive and gstreamer-send currently.

Migrate SDP generation to Unified Plan

---

certificate.go
datachannel_ortc_test.go
dtlstransport.go
examples/ortc-quic/main.go
examples/ortc/main.go
peerconnection.go
quictransport.go
quictransport_test.go

Instead of printing the error to stdout return the error to the user.
This may not be a hard error (as later certificates would have passed)
but it never is good to be in a state where you have certificates in a
broken state.
Resolves #586

Return error on certificate fingerprint failure

---

.github/lint-disallowed-functions-in-library.sh
quictransport.go

Relates to #361 
----
When this lands I am going to do one for every other library used by pion/webrtc!

Add lint to disallow fmt.* functions

---

.travis.yml
examples/ortc-quic/main.go
quicparameters.go
quicrole.go
quicrole_test.go
quictransport.go
quictransport_test.go

Taking a more extreme approach than #588... This patch
disables quic by default. The advantage here would be
that webrtc builds with older versions of go than
quic-go supports (currently 1.12+).

Disable quic by default; enable with build tag

---

peerconnection.go
peerconnection_media_test.go
peerconnection_test.go

Fixes regression in issue #449 caused by recent unified plan
changes.
Previously the PeerConnection would create invalid SDPs
when answering an offer that contained codecs it didn't
know about. Now it rejects them by setting the media format
to 0.
Related to #449

SDP: reject media tracks without matching codec

---

mediaengine.go

This will fix answers with H264 in the short term.
In the long term we need to update our examples and show how you need to probe this.

Update H264 default payload type to match Chromium

---

icetransport.go
peerconnection_close_test.go

When ICE is completely connected closing the mux is the proper way to
shut everything down. The Close is communicated down each transport.
The ICETransport mux is only available once ICE has completed however.
When shutting down the ICETransport if the mux isn't set close the
ICEGatherer if it has been set.
Resolves #608

Close ICEGatherer if mux isn't ready

---

.travis.yml
peerconnection_close_test.go

Test success depend on a condition that happens in a detached thread.
Update test to take the lock and assert the behavior explicitly.
Resolves #626

Fix flaky test TestPeerConnection_Close_PreICE

---

README.md
peerconnection.go
peerconnection_close_test.go
peerconnection_go_test.go

Before our RTPTransceiver logic would only allow Sendrecv to
match with another Sendrecv. Instead allow a SendRecv to be used
with a local Recvonly

Allow remote Sendrecv to be used with Recvonly

---

stats.go
stats_test.go

Add structs from [rtc-domstats](https://www.w3.org/TR/webrtc/#dom-rtcstats) spec so we can begin implementing the GetStats API.
Related to #610

WIP: Add Stats structs

---

dtlstransport.go
go.mod
go.sum
icetransport.go
peerconnection_close_test.go
quictransport.go

There are some direct usages of unexported fields of ICETransport
from non ice-related methods. This would be problematic when ice
once ice related code is moved to a separate packet. Added proxy
methods to ICETransport to avoid this.
Rel #646

Remove direct usage of unexported fields in ICETransport

---

ice_go.go
icegatherer.go
icetransport.go

ICEGatherer and ICETransport will no longer have a field of type API.
Instead every necessary settings are passed to these structs
one-by-one.
Rel #646

Removed API dependency from ice related structs

---

datachannel.go

This can help fix some race conditions where the data channel is opened before `onOpenHandler` is set up.

Immediately fire onOpenHandler if the DataChannel is already open

---

examples/README.md
examples/echo/README.md
examples/echo/jsfiddle/demo.css
examples/echo/jsfiddle/demo.details
examples/echo/jsfiddle/demo.html
examples/echo/jsfiddle/demo.js
examples/echo/main.go
examples/examples.json

The echo example demonstrates how to have Pion
send back to the user exactly what it receives
using the same PeerConnection.
Relates to #560
Co-authored-by: Patrice Ferlet <patrice.ferlet@smile.fr>

Add examples/echo

---

datachannel.go
sctptransport.go

it's expected for a open Datachannel to have an associated datachannel.Datachannel. Handling everything under the same lock guarantee that
I'm currently random getting this error (which this PR fixes), when trying to detach a channel in the open handler `datachannel not opened yet, try calling Detach from OnOpen`

Fix DC open

---

go.mod
go.sum
icecredentialtype.go
icecredentialtype_test.go
iceserver.go

https://www.w3.org/TR/webrtc/#dom-rtciceserver has the following default
```
credentialType = "password";
```
Update our enum to match that, currently we require users to specify
password

Default ICECredentialType to password

---

go.mod
go.sum
icegatherer.go
icetransport.go
peerconnection.go
peerconnection_go_test.go
peerconnection_test.go

Add ice trickle support

---

internal/mux/endpoint.go
peerconnection.go
rtpsender.go

Fix inconsistency with error handling when we have no candidate pairs.
Before we had custom code in RTP handling that would discard errors
if it was because we had no candidate pairs. Move this logic into the
mux so we have consistent behavior with Datachannels
This can be expected and is a soft failure. Every subsystem is expected
to handle lossy communication.
Resolves #706

Don't error when no candidate pairs

---

README.md
peerconnection.go
peerconnection_setlocaldescription_test.go

The fact that SetLocalDescription isn't called is erroneous, but should not result in a panic. It may be that we shouldn't even be processing incoming tracks until the local description has been set.
**Edit**: The approach taken to fix the panic is to just log and bail as is done in the rest of the function, rather than moving around the code to handle incoming tracks. I would appreciate suggestions for alternatives.
Fixes #563

Fix panic in openSRTP

---

dtlstransport.go
peerconnection.go
peerconnection_media_test.go
peerconnection_setlocaldescription_test.go
peerconnection_test.go

Store orphaned SRTP/SRTCP streams and discard them
when we close the PeerConnection
Resolves #729

Fix routine leak in drainSRTP

---

README.md
js_utils.go

With the result buffer wrapped in a js.TypedArray js will do the copy for us. See: https://github.com/WebAssembly/design/issues/1231#issuecomment-420466909

Reduce syscall/js calls needed to load Uint8Array

---

.travis.yml
datachannel_js.go
datachannel_js_detach.go
dtlstransport.go
mediaengine.go
peerconnection.go
peerconnection_js.go
quictransport.go
sctptransport.go

Eventually this will be added to golangci-lint, but for now
we have to do it manually
Relates to #106

Add godox to .travis.yml

---

icegatherer.go

Currently the ICEGather will crash if trickle is enabled and
OnLocalCandidate hasn't been defined. This adds a simple nil check
to make sure we don't crash if the user doesn't set a OnLocalCandidate
callback.

Guard against nil OnLocalCandidate handler

---

examples/pion-to-pion-trickle/README.md
examples/pion-to-pion-trickle/answer/main.go
examples/pion-to-pion-trickle/offer/main.go
go.mod
go.sum
ice_go.go
icecandidate.go
peerconnection.go

This cherry-picks @hugoArregui work and adds an example
I had to update the gathering code to only start when signaling is in a stable enough state. If someone emits candidates before the other side is ready it causes Chrome/Pion to fail

Trickle Example

---

icecandidate.go
icecandidate_test.go

Candidate field should always start with "candidate:" prefix

Fix ICECandidateInit ToJSON

---

examples/pion-to-pion-trickle/answer/main.go
examples/pion-to-pion-trickle/offer/main.go

Close Response body right away and use http.Server to block
instead of select{}

Simplify pion-to-pion-trickle example

---

examples/pion-to-pion-trickle/answer/main.go

Answer was sending candidates to itself. This was slowing down
ICE since all we had was prflx candidates on the offer side.

Fix pion-to-pion-trickle signaling

---

README.md
examples/echo/jsfiddle/demo.js
examples/echo/main.go
mediaengine.go
peerconnection.go

This fixes the echo program so it works properly on Safari
and Firefox, where the preferred offered dynamic media type
is not 96/VP8. It loads MediaEngine with codecs found in the
offer and then uses the payload type of the offer's preferred
video codec in the answer.

Fix echo for Safari and Firefox

---

dtlsrole.go
dtlsrole_test.go
peerconnection.go

Take into consideration if remote is running DTLS as a
client/server. Before we ignored this value and we could
enter cases where DTLS would never connect.
Resolves #494

Parse DTLS setup in SetRemoteDescription

---

README.md
peerconnection.go
peerconnection_go_test.go

I noticed `a:setup=actpass` showing up twice in each media description in an SDP. It is already being added in the `addTransceiverSDP` and `addDataMediaSection` methods.

Remove doubling of connection setup in SDP creation

---

README.md
icegatherer.go
icegatherer_test.go

onLocalCandidateHdlr was called in one candidate per one goroutine.
It is not guaranteed to be called in-order, and nil can be sent before the final candidate.
Before this fix, nil is sent before sending all candidates 8-10 times per 10 tries on my local environment.

Fix possible ill-order of OnLocalCandidate call

---

sctptransport.go

Pass association to readLoop instead of accessing SCTPTransport
inside readloop. It is possible that before the read loop starts
the SCTPTransport assocation could be cleared, this would cause
us to pass a  nil assocation to pion/datachannel
Resolves #571

Guard against SCTPTransport being closed during start

---

datachannel_test.go
package.json

Upstream has fixed an issue that was blocking one of our tests. Enable
the test and bump the wrtc version.

Bump wrtc used for WASM testing

---

ice_go.go
icegatherer.go
icegatherer_test.go
settingengine.go
settingengine_test.go

Resolves #835
Added these parameters configured via SettingEngine
* NAT1To1IPs []string - an array external IP addresses
* NAT1To1IPCandidate - target candidate the external IP address is used for ("host" or "srflx")
See #835 for details.

Support 1:1 NAT option

---

README.md
peerconnection.go
peerconnection_media_test.go

When rejecting media, the identification-tag (i.e. media ID) must
be removed from the bundle in addition to setting the m-line port
to zero.
See https://tools.ietf.org/html/draft-ietf-mmusic-sdp-bundle-negotiation-39#section-8.3.4
Fixes #840

Fix answer bundle for rejected media

---

constants.go
peerconnection.go
peerconnection_media_test.go
sdpsemantics_test.go

If we receive an unknown SSRC and we have a single
media section with no SSRCes declared fire an OnTrack
with that stream
Resolves #880

Handle undeclared SSRCes

---

datachannel_go_test.go
datachannel_test.go
go.mod
go.sum
icegatherer_test.go
icetransport_test.go
peerconnection_close_test.go
peerconnection_go_test.go
peerconnection_media_test.go

Fix tests that didn't properly close and add
test.CheckRoutines everywhere. No changes in pion/webrtc
but we did catch hanging thread in pion/ice

Fix all routine leaks in tests

---

datachannel.go
datachannel_go_test.go
datachannel_ortc_test.go
datachannelparameters.go
examples/ortc/main.go
icetransport.go
peerconnection.go
peerconnection_media_test.go
sctptransport.go
sctptransport_test.go

Before we computed DataChannel IDs before signaling, this
is incorrect because IDs must take into account if we are
running an DTLS Client or Server.
This updates the DataChannel ID generation code to take this
into account before generating a streamId.
Resolves #908

Properly generate DataChannel streamId

---

ice_go.go
icegatherer.go
icegatherer_test.go
icetransport.go
peerconnection.go

Use values directly from SettingValues instead of just copying
when calling NewICEGatherer. This greatly reduces the LoC and makes
the public API a little cleaner.
Resolves #872

Only create ICEGather via API

---

datachannel.go
datachannel_test.go
peerconnection.go

DataChannel readyState should be set to Closed on PeerConnection
shutdown. If not properly set it would attempt to interact with
state that doesn't exist after the PeerConnection has been Closed.
Setting the readyState is also clearly defined in the W3C webrtc-pc
Resolves #915

Properly set DataChannel readyState on Close

---

datachannel.go
datachannel_test.go
peerconnection.go

Match W3C WebRTC and allow a DataChannel to close even before
signaling happens. When SCTPTransport opens make sure
to check the readyState first.

Allow user to Close DataChannel before signaling

---

datachannel.go
stats_go_test.go

Recent changes allow a dc to have a nil id before it's actually open, but stats used to require the id.

Check for dc.id in stats

---

icegatherer.go
icegatherer_test.go
settingengine.go

Users can now generate MulticastDNS candidates by enabling this option
in the SettingEngine.

GenerateMulticastDNSCandidates in SettingEngine

---

datachannel.go

checkDetachAfterOpen incorrectly accesses detachCalled without holding the lock
Relates to #838

Fix race in checkDetachAfterOpen

---

configuration_common.go
configuration_test.go
peerconnection.go

Currently we error if a STUN URL passed to Configuration.ICEServers
contained a query parameter. Fix this by using the getICEServers
function that sanitizes these for us.

Properly sanitize STUN urls

---

.travis.yml

Share modules cache directory with the host.
Use i386/golang:1.13-alpine image to reduce docker pull size half.

Speed-up i386 test

---

datachannel.go
datachannel_test.go

OnOpen handler is sometimes called with a huge delay in TestDataChannel_Open and causes handler_should_be_called_once failure.
This commit minimizes mutex lock scope around handler registration and removes redundant mutex.
Also, add sleep before closing PeerConnections in TestDataChannel_Open to ensure all messages are processed.
```
--- FAIL: TestDataChannel_Open (0.54s)
--- FAIL: TestDataChannel_Open/handler_should_be_called_once (0.54s)
datachannel_test.go:91: 
Error Trace:	datachannel_test.go:91
Error:      	"%!s(chan bool=0x81c310)" should have 1 item(s), but has 0
Test:       	TestDataChannel_Open/handler_should_be_called_once
```
This error should be fixed by this PR.
~might reduce #938~ and errors shown in #943

Reduce blocking in datachannel handler

---

.travis.yml

Run lint/test/WASM-test/i386-test in parallel.
Node is upgraded to v12 as v11 is EOL-ed.

Update CI script

---

mediaengine.go
mediaengine_test.go

PopulateFromSDP did not properly handle Offers with Datachannels, now
we only parse a MediaSection that has a name of 'audio' or 'video'
Resolves #953

Fix PopulateFromSDP with Application MediaSection

---

.travis.yml

coverpkg expects trailing comma, also filter examples instead of
removing them

Update coverpkg calculate

---

README.md
peerconnection.go
peerconnection_media_test.go

Add a new public method, GetRegisteredRTPCodecs, under PeerConnection to allow access to get the registered list of RTPCodec from the underlying MediaEngine for developers who want to build libraries on top of pion.
Resolves #966

Expose an API to get a list of registered RTPCodec from PeerConnection

---

README.md
mediaengine.go
mediaengine_test.go

As defined in: https://tools.ietf.org/html/rfc4855#section-3
```
Media subtype names are commonly shown in lower case.
These names are case-insensitive in both places.
```
As well as: https://tools.ietf.org/html/rfc4288#section-4.2
```
Both type and subtype names are case-insensitive.
```

mediaengine: Case-insensitive media subtype check

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Add functional option to set PartitionHeadChecker to detect the beginning of the frame partition.
It avoids dropping the first packet. (which is often a keyframe, so, loosing the first packet sometimes causes large delay to start.)
requires https://github.com/pion/rtp/pull/26 (ready)

Add option to detect partition head in SampleBuilder

---

icetransport.go
peerconnection_close_test.go
peerconnection_media_test.go

Calling ConnectionStateChange handler during Stop caused mutex
deadlock. Add another Mutex to protect handler pointer to
avoid the deadlock.
`TestPeerConnection_Close_DuringICE` is added to reproduces the deadlock in old code.
Fixes #996

Fix deadlock during ICETransport.Stop

---

peerconnection.go
peerconnection_media_test.go
sdp.go

SDP parsing only supported one ssrc per media section.
Now we properly can handle multiple.
Resolves #1014

Add test for multi-track PlanB signaling

---

README.md
rtpsender.go

The webrtc spec in https://www.w3.org/TR/webrtc/#dom-rtcrtpsender sais an RtpSender object has a read-only attribute track. We expose this attribute via a 'Track()' method.
[`RTPReceiver`](https://github.com/pion/webrtc/blob/v2.2.0/rtpreceiver.go#L54) already exposes this attribute in the same way, so not including it in `RTPSender` was likely just an oversight.

RTPSender: Expose the 'track' attribute as per spec

---

peerconnection.go

The data race detector detects a race if PeerConnection.ConnectionState is called while PeerConnection.updateConnectionState is changing the connection state.

Fix race in PeerConnection.ConnectionState

---

README.md
icegatherer.go
peerconnection.go

It would also be possible to swap the order of event execution but, but that require breaking change to the execution flow maybe breaking some apps. (First setting state completed then executing onLocalCandidateHdlr and then onStateChangeHdlr but that still breaking change to the execution flow).
This is way safer.
Fixes #1051.

Adding OnICEGatheringFinish.

---

peerconnection.go
peerconnection_media_test.go
peerconnection_renegotation_test.go

When offering always put application first. Before during re-negotation
we would break the order if media sections because we would always place
it last. Instead of remembering what order the application was place
just always place it first.

Put application media section first

---

datachannel_js.go
js_compare.go
js_compare_legacy.go
js_utils.go
peerconnection_js.go

Replace js.Undefined() and js.Null() comparisons with IsUndefined() and
IsNull().
Directly comparing js.Value instances to js.Undefined() and js.Null() was deprecated in Go 1.14. See: https://golang.org/doc/go1.14#wasm

Replace js.Value comparisons deprecated in Go 1.14

---

peerconnection.go

Move this from Error -> Warn. Now that re-negotiation has landed users
will see this a lot more, and it isn't helpful by default. We still want
this message in case users are trying to debug if an OnTrack isn't
fired.

Change incoming orphaned SSRC log level

---

icegatherer.go
icegathererstate.go
peerconnection_go_test.go

Don't call handlers in goroutine to guarantee the ordering and avoid changing internal state during callback.
Fixes #1071

Fix ICEGatherer state change callback order

---

peerconnection.go
peerconnection_renegotation_test.go

Each negotation must be finished before processing the next one.
Before we would process multiple calls at once, and since they are
performed async we would have undefined behavior.
Resolves #1074

Process SetRemoteDescription calls serially

---

e2e/e2e_test.go
mediaengine.go
mediaengine_test.go

When making MediaEngine case-insensitive in 20f2d18
Opus was upcased when adding to SDP. This returns it
to what it was before
Resolves #1078

Don't upcase opus when adding to SDP

---

README.md
pkg/media/ivfreader/ivfreader.go

Use `io.ReadFull` to read from the `io.Reader`.
Fixes #1086

Make the IVF reader able to read from a network connection

---

README.md
sdp.go
sdp_test.go

If the remote description contains rtx information via a `ssrc-group`,
the extra `ssrc` entries must be ignored to ensure thats no receiver
is added for them.
This can solve issues like `Incoming unhandled RTP ssrc(1858531374)` if
those are caused by a wrong receiver getting started for the rtx ssrc
but not for the track ssrc, based on the ssrc/transceiver oder in the
remote description.
Until rtx is properly supported, this change fixes the imediate issue
that some remote streams are randomly not received because of a remotes
rtx information.
Fixes: #1081
Related: #1083

Ignore rtx ssrc from FID group when extracting tracks

---

datachannel.go
sctptransport.go
sctptransport_test.go

Concurrent call of generateDataChannelID caused data race.
Fixes #1103

Fix DataChannel open race

---

dtlstransport.go
settingengine.go
settingengine_test.go

Set windows size of each protocol by:
- SetDTLSReplayProtectionWindow
- SetSRTPReplayProtectionWindow
- SetSRTCPReplayProtectionWindow
Fixes #1098

Add replay protection setting to SettingEngine

---

mediaengine.go

Tested in ion, chrome and iphone7 can see each other by setting to H264 or VP8!
The IOS supported profile fmtp is:
**level-asymmetry-allowed=1;packetization-mode=1;profile-level-id=42e01f**
42e01f means: 
**Constrained Baseline Profile Level 3.1**
Fixes #1090

Support new codec with fmtp

---

rtpreceiver.go

I saw panics like this, when an RTPTransceiver is stopped.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9479b2]
goroutine 37117 [running]:
github.com/pion/srtp.(*ReadStreamSRTCP).Close(0x0, 0x0, 0x0)
github.com/pion/srtp@v1.2.7/stream_srtcp.go:66 +0x42
github.com/pion/webrtc/v2.(*RTPReceiver).Stop(0xc011d4f3e0, 0x0, 0x0)
github.com/pion/webrtc/v2@v2.2.4-0.20200310073244-be9fde1fd3cf/rtpreceiver.go:139 +0xfb
github.com/pion/webrtc/v2.(*RTPTransceiver).Stop(0xc000ced300, 0x1137798, 0x10)
github.com/pion/webrtc/v2@v2.2.4-0.20200310073244-be9fde1fd3cf/rtptransceiver.go:55 +0x15a
github.com/pion/webrtc/v2.(*PeerConnection).Close(0xc0395a1d40, 0xc04a5cbbc0, 0xc7f200)
```
If a RTPReceiver is stopped before it ever receivers, no streams are
attached to it which can be …

Fix RTPReceiver Stop race

---

peerconnection.go
peerconnection_renegotation_test.go

For some reason edge prechromium does not like media data section before video/audio in the sdp.
It generates the following error:
> 0: Unable to get property 'state' of undefined or null reference    rtcpeerconnection.js (1016,1)
Fixes #1113

Append media data section after transceivers

---

README.md
examples/broadcast/README.md
examples/custom-logger/README.md
examples/data-channels-create/README.md
examples/data-channels-detach-create/README.md
examples/data-channels-detach/README.md
examples/data-channels/README.md
examples/pion-to-pion/README.md
examples/pion-to-pion/answer/Dockerfile
examples/pion-to-pion/offer/Dockerfile
examples/play-from-disk/README.md
examples/reflect/README.md
examples/rtp-forwarder/README.md
examples/save-to-disk/README.md

I found `go get github.com/pion/webrtc/examples/data-channels` fails.
Currently download instructions should contain 'v2'.
None.

Update how to install in example projects

---

README.md
pkg/media/oggwriter/oggwriter.go

Update to properly close an oggwriter when writing to a stream.

Close stream in oggwriter

---

peerconnection.go
peerconnection_renegotation_test.go

During re-negotiation we didn't properly SSRCes we had already handled.
This makes sure to loop the existing transceivers and assert we don't
try to handle the same SSRC again.
Resolves #1122

Don't call OnTrack for same SSRC multiple times

---

README.md
examples/broadcast/main.go
examples/rtp-forwarder/main.go
examples/save-to-disk/main.go

I found some example projects use `AddTransceiver`, which is a deprecated method.
So I updated those examples to use `AddTransceiverFromKind`.
None
---
I also found the method is used in `peerconnection` and some tests.
If there is no reason to use `AddTransceiver` in those codes, I am happy to fix them as well.

Update examples to use AddTransceiverFromKind

---

peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_setlocaldescription_test.go
sdpsemantics_test.go

I found `AddTransceiver` is used in `peerconnection` and some tests, although it is a deprecated method.
So I updated those code except `TestAddTransceiver` to use `AddTransceiverFromKind`.
This PR is continued from #1128.

Use AddTransceiverFromKind

---

dtlstransport.go
settingengine.go

Sometimes the replay protection of SRTP and SRTCP needs to be disabled.
This change adds disableSRTPReplayProtection and
DisableSRTCPReplayProtection helpers to SettingEngine.

Add helpers to disable replay protection

---

stats_go_test.go

Add sleep to ensure counting the last packet.
Fixes #1127

Fix TestPeerConnection_GetStats stability

---

README.md
peerconnection_test.go

Fixes potential issue with calling non-formatting functions with strings that maybe interpreted as a format string. 
As an example `log.Trace("%v")n` would end up logging "%!v(MISSING)" instead.

Fix potential issue of misinterpreting format string

---

README.md
networktype.go
networktype_test.go

Added function for setting network types from external side;
This patch allows to populate network types from external user's side. It might be data from yaml config or simple string slice.
Since function for creating network type from string is private we can't move this function to user side.

Populate network types from config

---

peerconnection.go

Use populateLocalCandidates in LocalDescription. Before we incorrectly
never populated candidates.
Resolves #1143

Populate candidates in LocalDescription

---

icetransport_test.go
peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotation_test.go

In SetLocalDescription guard iceGatherer.Gather by checking state.
We don't put this check inside Gather because ORTC doesn't have the
function as re-entrant
Resolves #1144
Co-authored-by: Jerko Steiner @jeremija

Only call iceGatherer.Gather once

---

peerconnection.go
peerconnection_media_test.go

This might cause problems for existing users who have gotten used to the fact that a new transceiver will always be created when `AddTrack` is called.
I'm not sure if we can simply merge it to master and tag as a patch/minor release. Would greatly appreciate feedback!
Fixes #1155

Ensure existing transceivers are reused

---

sdp.go
sdp_test.go

This modification will only keep incoming tracks from media sections
with `a=sendrecv` or `a=sendonly` attributes. This modification is not
necessary for pion-to-pion peer connections, but for browser-to-pion
connections using Unified Plan.
Background:
When a `RTCPeerConnection#removeTrack()` is called in the browser and
the connection is renegotiated, the browser (tested in Firefox 75.0)
will change the media section attribute to `a=recvonly` from
`a=sendrecv`, or `a=inactive` from `a=sendonly`, but will keep the same
`a=ssrc:<ssrc>` associated with the same media (mid) section.
Previously, when a remote track obtained with Pion's `OnTrack()` handler
was being read from, and this remote track was later removed in the
browser, the track's `Read()` method would never return `io.EOF` …

Filter out non-sending incoming tracks

---

peerconnection.go

Fix some typos where "tranceiver" was used instead of "transceiver".

Fix "tranceiver" instead of "transceiver" typos

---

peerconnection.go
peerconnection_media_test.go

This tries to better match the JSEP spec and will fix at least two
issues:  #1171 and #1178
* Move transceiver selection/creation in SetRemoteDescription and
CreateOffer
* In SetRemoteDescription also create new Transceivers of type recvonly
when no satisfying transceiver is available
* In CreateOffer generate unique mid in number format avoiding possible
collisions with remote provide mids and to also already handle a future
implementation of m= section rejection and reuse
* Now generateMatchedSDP will just find the transceivers with the
required mid since they are already selected previously.
More details in these extract from JSEP:
JSEP 5.10 (Applying a Remote Description) says:
```
For each m= section, the following steps MUST be performed
[...]
If the m= section is not associated …
```

Move transceiver selection inside SetRemoteDescription and CreateOffer

---

peerconnection.go
peerconnection_media_test.go
rtpsender.go

Only start senders that were negotiated.
Since `startTransports`/`startRenegotiation` start rtp senders in a goroutine,
an user could call AddTrack/Add*Transceiver/RemoveTrack causing a not negotiated
sender track ssrc to be started.
Fixes #1169

Start only negotiated senders

---

peerconnection.go
peerconnection_media_test.go
sdp.go
sdp_test.go

From PR #1158 during negotiation every required transceiver is assigned
to a specific media section (using the media section mid value).
The same should be done when starting receivers. We should start the
receiver assigned to the media section of that track.

Start the right receiver

---

icetransport.go

The gatherer attached to ICETransport must check wether it actually has
an agent before trying to use it. This avoid a panic when when the
gather is closed while adding or setting remote candidates.
This resolves the following panic:
```
May 07 11:30:16  run.sh[8448]: panic: runtime error: invalid memory address or nil pointer dereference
May 07 11:30:16  run.sh[8448]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0x9b5cd2]
May 07 11:30:16  run.sh[8448]: goroutine 19 [running]:
May 07 11:30:16  run.sh[8448]: github.com/pion/ice.(*Agent).ok(0x0, 0xc0018d3e80, 0x10)
May 07 11:30:16  run.sh[8448]:         github.com/pion/ice@v0.7.10/agent.go:166 +0x22
May 07 11:30:16  run.sh[8448]: github.com/pion/ice.(*Agent).run(0x0, 0xc004368938, 0x6, 0xc000438600)
May 07 11:30:16 …
```

Cure ICETransport gatherer agent race

---

README.md
datachannel.go

This is the second half of https://github.com/pion/datachannel/pull/60:
> Empty messages should be sent as one zero byte. When receiving an Empty
> message, the contents should be ignored.
> 
> Currently pion/webrtc converts zero-byte messages into single null-byte messages and datachannels transmits it as a regular message. This fixes datachannels to send the correct payload and strip the payload for Empty messages.
> 
> I'll send a PR for webrtc to remove the conversion from webrtc too.
Now that datachannel handles Empty messages correctly, webrtc should pass them to datachannel at they are.

Fix handling of Empty DataChannel messages

---

README.md
ice_go.go
icecandidate.go
peerconnection_js.go
peerconnection_js_test.go

On Firefox, the RTCIceCandidate interface appears to just be an RTCIceCandidateInit in disguise. That is, it does not have properties for each individual component of the candidate line. It only has the raw SDP string in the candidate property.
This change falls back to parsing the candidate line if some expected property is missing when preparing the candidate for the callback OnICECandidate.
https://developer.mozilla.org/en-US/docs/Web/API/RTCIceCandidate
https://caniuse.com/#feat=mdn-api_rtcicecandidate_priority
Let me know what you think!

WASM: Fallback to parsing SDP line for OnICECandidate

---

peerconnection_js.go

This allows us to make a new PeerConnection from an RTCPeerConnection js.Value.
My use case for this is a Go package that handles the signalling parts, but leaves the rest to the application. A JS application can pass its own PeerConnection initialised with whatever datachannels/streams then wait for ICE/signalling to finish.

WASM: allow PeerConnection to be initialised from a JS object

---

peerconnection_media_test.go
rtpreceiver.go
rtpsender.go

This makes checking for these errors much more robust
than doing a string comparison.
This is a follow-up to #1222 (which I was delighted to see). There are other possible errors we could use (io.ErrUnexpectedEOF, io.EOF, a new exported webrtc error var), but this one seemed appropriate.
Hopefully we could merge this or something like it before tagging a new release, to avoid backwards compatibillty problems.

use exported errors for reads/writes to stopped rtp i/o

---

pkg/media/h264writer/h264writer.go
pkg/media/h264writer/h264writer_test.go

Currently it only supports non-interleaved mode
Therefore, only 1-23, 24 (STAP-A), 28 (FU-A) NAL types are allowed
Related #889

Add H264 writer

---

configuration_common.go
peerconnection_go_test.go

Before ICEServers wasn't thread safe. If a Configuration
was shared among multiple PeerConnections the sanitization logic
could cause race conditions.
Resolves #1246

Copy ICEServers when creating new PeerConnection

---

README.md
dtlsrole.go
dtlstransport.go
go.mod
go.sum

This matches rfc5763, setup:active is RECOMMENDED
Relates to #494

Set role when actpass remote to DTLSRoleClient

---

track.go
track_test.go

If Read is called before AddTrack a panic would happen.
Check that the Track has a Receiver and return an error if it doesn't
Resolves #1240

Don't allow reading from send track

---

.github/.ci.conf
.github/assert-contributors.sh

Lint scripts are automatically synchronized from pion/.goassets.
Please don't edit these files directly.

Fix synchronized lint script

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

`SampleBuilder` held reference to outdated packets when the `SequenceNumber` is jumped.

Unreference garbage in SampleBuilder buffer

---

peerconnection_go_test.go

Test would compare PendingLocalDescription while it was still gathering.
If a candidate trickled between calls it would fail the test.

Fix race in TestPopulateLocalCandidates

---

peerconnection.go
peerconnection_go_test.go
sdp.go
sdp_test.go
settingengine.go

This commit adds an option to put DTLS Fingerprint specification
at the media description level rather then the session description
level. This enhances compatibility with some 3rd party webrtc
implementations (notably Kurento).
Note: This will require pion/sdp PR 57 to get merged. I'm marking this PR as a draft until then.

Media Level Fingerprints Configuration Option

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

It unexpectedly unreferenced all packets
when sequence number is decreased more than 2.
Fix regression from #1269

Fix SampleBuilder packet unref

---

peerconnection.go
peerconnection_test.go

Before users could pass a SessionDescription with a 0 type. This would
be discarded silently. Now we return an error that matches browser
behavior.
Resolves #1297

Assert SDPType in setDescription

---

README.md
datachannel_js.go

Use links and a badge from https://pkg.go.dev.
https://pkg.go.dev/badge/ supports creating a badge now.
~Fixes #...~

Update godoc link to pkg.go.dev

---

examples/ice-tcp/index.html
examples/ice-tcp/main.go
go.mod
go.sum
icegatherer.go
icetcp.go
settingengine.go
settingengine_test.go

This adds support for enabling ICE TCP by providing `ice.TCPMux` to `settingEngine`. The global state in `pion/ice` was removed and users can now specify their own `net.Listener` when creating a `ice.TCPMux`. A convenience function `NewICETCPMux` was added that returns a new instance of `ice.TCPMuxDefault`.
See https://github.com/pion/ice/pull/254 for more details.

Upgrade pion/ice to v2.0.0-rc.9

---

peerconnection.go
peerconnection_renegotiation_test.go
sctptransport.go

Before when creating an offer during renegotation we didn't support
adding a DataChannel.
Resolves #1361

Support creating a DataChannel during renegotation

---

README.md
examples/play-from-disk/main.go

Wrong error variable was checked and redundant parentheses in
play-from-disk example.

Fix error checking

---

go.sum
peerconnection.go
peerconnection_renegotiation_test.go

Fixes a race condition that occurs when the local media (transceivers) are mutated during the offer generation process.
Resolves an issue where an offer is created with no `mid` causing the error below:
The test is not great, since it depends on the performance of the executor. I was able to consistently reproduce locally with it though.

Fix: CreateOffer race condition

---

README.md
peerconnection.go
peerconnection_go_test.go

It's an anti-pattern when using sync.RWMutex in golang.
After acquiring two reader privilege of a rwlock, it will deadlock if
another routine tries to acquire a writer lock.
In pion/webrtc, this calling sequence might happen when calling
GetTransceivers during track events.
Resolves #1425

Avoid acquiring two reader privilege of a lock

---

go.sum
peerconnection.go
peerconnection_renegotiation_test.go

Ensures negotiation needed handlers complete execution before closing peer connection.
Resolves #1401

Fix: Flakey OnNegotiationNeeded tests

---

dtlstransport.go

This modification attempts to fix a deadlock happens when closing a
peer-connection.
The deadlock scenario is:
- routine-1: DTLSTransport.Stop is called during closing, which holds
the writer-lock of DTLSTransport, and it blocked by accepting from
session.closed channel when trying to close SRTPSession.
- routine-2: its stacks located in the routine launched in
srtp.session.start(...), this routine should close the session.closed
channel, however, it blocked when sending to
srtp.SessionSRTP.session.newStream
- routine-3: this routine should call strp.SessionSRTP.AcceptStream
to release routine-2. However, it blocked when calling
DTLSTransport.getSRTPSession(), it requires the reader-lock.
To resolve this issue, the instance of SessionSRTP is kept in
atomic.Value and avoid the requirement …

Keep sessions in atomic.Value

---

errors.go
quictransport.go

Fix typo made when updating golangci-lint

Fix typo `Quick` -> `Quic`

---

icegatherer.go
icegatherer_test.go
peerconnection_go_test.go
settingengine.go

GenerateMulticastDNSCandidates -> SetICEMulticastDNSMode.
Before a user wasn't able to disable mDNS. By changing it we can
do more with this API.

Rename SettingEngine mDNS Config option

---

README.md
rtpreceiver.go

Fix a race on simulcast, where track or peer is removed before tracks are received.
Fixes #1471

Fix receiver close stream race close #1471

---

peerconnection.go
peerconnection_test.go

SetRemoteDescription was not properly returning errors. Fix and add test
to make sure we don't regress again in the future.
Resolves #1210
Resolves #1473

setDescription was incorrectly discarding errors

---

peerconnection.go

Fix race where negotiation check sender track, while sender still not created.
Fixes #1411

Fix sender nil on negotiation check step 5.3.1

---

peerconnection.go
sessiondescription.go
sessiondescription_test.go

This will allow to re-use the internally parsed sdp, and prevent parsing multiple times and save some cpu cycles.

Add SessionDescription Unmarshal helper

---

README.md
pkg/media/h264reader/h264reader.go
pkg/media/h264reader/h264reader_test.go
pkg/media/h264reader/nalunittype.go

Continuing work started by @chertov in https://github.com/pion/webrtc/pull/976
Moved h264reader from examples to inside library. And adapted little bit code to look like ivfreader.
For a moment it reads all frames in 1 call. It should be improved in later PRs.

Add  h264reader and test for it

---

.github/.ci.conf
README.md
peerconnection.go

I noticed that, when using the `OnNegotiationNeeded` callback, I got called back continuously, every time a negotiation finished. As far as I can tell, this is because `checkNegotiationNeeded()` was comparing an MSID against `track.StreamID()`, which isn't quite an MSID, so it never matched.

Compute the track's MSID to compare with the one in the SDP.

---

peerconnection.go

Reduce the amount of code that is running if we don't need this.
Relates to #1494

Don't run OnNegotiationNeeded if handler not set

---

dtlstransport.go
peerconnection.go
peerconnection_media_test.go
rtpsender.go
srtp_writer_future.go
track_local_static_test.go

* Return error to user when remote doesn't support codecs
* Assert that a unadded track returns an error on Write
* Assert that a added track doesn't error even when disconnected
Relates to #1526

Improve TrackLocal error handling

---

track_local_static.go
track_local_static_test.go

Reduce a sharp edge in the public API. Before we would keep a reference
internally. Users would be suprised when values on the passed
*rtp.Packet would change.
TODO write Benchmark

Use rtp.Packet instead of *rtp.Packet in APIs

---

errors.go
mediaengine.go
mediaengine_test.go
peerconnection.go
rtpcapabilities.go
rtpcodec.go
rtpreceiver.go
rtpsender.go
rtptransceiverdirection.go
sdp.go

RegisterHeaderExtension now allows users to enable headers depending on
the type of transceiver that was created.
Also expose GetParameters on RTPSender and RTPReceiver
Co-authored-by: OrlandoCo <luisorlando.co@gmail.com>
Resolves #1554

Allow extensions to be configured with direction

---

track_local_static.go

This is analoguous to remote tracks, but returns just RTPCodecCapability
rather than RTPCodecParameters.
This doesn't return the same type as `remote.Codec`.  Perhaps the latter should be renamed?
Fixes #1575.

Implement Codec() for local static tracks.

---

mediaengine.go
mediaengine_test.go
sdp_test.go

Export mime types from media engine for matching. Helpful when trying to get codec from a track

Export mime types

---

constants.go
dtlstransport.go
errors.go
peerconnection.go
peerconnection_media_test.go
webrtc.go

When a new SSRC is seen we start a Read loop for the packets. However if
we only see one packet this loop will just sit forever. If a user
doesn't send us enough packets to finish probing it will prevent any
subsequent streams from being probed.
Relates to #1345

Fix Simulcast routine leak

---

interceptor_track_local.go

Before we would panic if atomic was nil. Add a type assert as well so
that we handle gracefully.
Resolves #1585

Fix interceptorTrackLocalWriter.WriteRTP cast

---

errors.go
icetransport.go
peerconnection_go_test.go

We didn't properly pass a context to the ICE Agent. We would leak
routines if closed while connecting.

Don't leak ICETransport routines

---

README.md
examples/README.md

List most popular features/benefits of Pion WebRTC.
Resolves #1279
Co-authored-by: ZHENK <chengzhenyang@gmail.com>

Add features matrix to the README

---

README.md
go.mod
go.sum
rtpreceiver.go
rtpreceiver_test.go
track_remote.go
vnet_test.go

Previously, Reading RTP or RTCP packets from a peer would block until a packet was received, or the connection was terminated. This change allows you to set a deadline, after which the read function will return a timeout error and you can get on with other things.

Added SetReadDeadline to RTPReceiver

---

rtpreceiver.go
track_remote.go

- Refine RTPReceiver.SetReadDeadline behavior
>  Instead of iterating over r.tracks, just calling r.tracks[0]
directly. This behavior follows RTPReceiver.Read.
- Add RTPReceiver.SetReadDeadlineSimulcast
> Its fingerprint follows RTPReceiver.ReadSimulcast.
- Refine RTPReceiver.setRTPReadDeadline
> It will only timeout the RTP stream for the track makes the call.
Refine the fix for https://github.com/pion/webrtc/issues/1553, PR: https://github.com/pion/webrtc/pull/1611

Refine SetReadDeadline behavior

---

iceserver_test.go
peerconnection_test.go

This only checks they are being parsed with no error, it doesn't
actually do anything useful with them.
Fixes #...

Add IPv6 addresses to some tests.

---

examples/simulcast/main.go
mediaengine.go
mediaengine_test.go

Chrome is failing to signaling if the remote peer offers RID/MID so
disabling by default.
Relates to pion/example-webrtc-applications#87

Don't enable RID/MID Extension Headers by default

---

mediaengine.go
peerconnection.go
settingengine.go
settingengine_test.go

If an API is shared between PeerConnections they would use the same
MediaEngine. A MediaEngine contains negotiated PayloadTypes so if the
PeerConnections were answering you would end up in invalid states.
Add DisableMediaEngineCopy to SettingEngine in case user needs old
behavior.
Resolves #1662
Fixes #...

Disable MediaEngine Copy by Default

---

peerconnection.go
settingengine_test.go

Assert that the MediaEngine used by the PeerConnection is in the state
we expect
Relates to #1662

Improve MediaEngine Copy tests

---

mediaengine.go
mediaengine_test.go

Fix register the same codec, otherwise addTransceiverSDP will add duplicate codec sdp
Otherwise addTransceiverSDP will add duplicate codec sdp
Fix https://github.com/pion/ion-sfu/issues/425
```
v=0
o=- 5454648987554646034 1613488747 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 56:62:E1:01:34:08:29:A2:72:E2:0E:28:4E:C6:C4:48:C9:C2:18:72:06:CF:A3:C9:2A:49:30:4F:6E:90:C9:89
a=group:BUNDLE 0 1 2 3 4
m=audio 9 UDP/TLS/RTP/SAVPF 111 111
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:KObOgVaHjOnnAtdX
a=ice-pwd:FMuiwaSPGdKPtXpjVLBaNoEMUjpKOson
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=rtpmap:111 opus/48000/2
a=fmtp:111 minptime=10;useinbandfec=1
a=ssrc:2193652934 cname:webm_0xc000163b80
a=ssrc:2193652934 msid:webm_0xc000163b80 audio …
```

Fix register the same codec

---

track_local_static.go
track_local_static_test.go

This avoids one allocation for every write.

Use a pool in Write and WriteRTP

---

datachannel_go_test.go
datachannel_test.go
dtlstransport_test.go
interceptor_test.go
peerconnection_close_test.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
peerconnection_test.go
rtpreceiver_test.go
rtpsender_test.go
sdpsemantics_test.go
settingengine_test.go
stats_go_test.go
track_local_static_test.go

Instead of explicitly closing each PeerConnection use helper.
No change in test behavior, just makes code more consistent.

Use closePairNow in tests

---

mediaengine.go
mediaengine_test.go

It addresses the issue that unable to updateHeaderExtension for cloned
MediaEngine, which is resulted from previous commit:
c8b7aa386a92100a0377fd32660c810d6e4e7e28
Fixes a possible(?) side-effect from the PR for #1662

Fix updateHeaderExtension for cloned MediaEngine

---

peerconnection.go
peerconnection_go_test.go
rtptransceiver.go

* When a local peer connection has a single transceiver with a `sendrecv` direction, and the remote has a transceiver with a `recvonly` direction, the local peer connection must change the transceiver direction to `sendonly`
* When a local peer connection has a single transceiver with a `recvonly` direction, and the remote has a transceiver with a `recvonly` direction, the local peer connection must create another transceiver with a `sendonly` direction
* A unit test is added to cover all possible cases
This issue is causing the infamous fatal error "Answer tried to set recv when offer did not set send" with Firefox.
This fixes #717 and closes #1199 and #1666

Set answer direction as sendonly when offer direction is recvonly

---

dtlstransport.go
dtlstransport_test.go

Before we would set the PeerConnection to failed, but we would leave the
DTLSTransport. This means that a user could still interact with the
other transports.
Relates to #1708

Close DTLS when fingerprint verification fails

---

fmtp.go
fmtp_test.go
mediaengine.go
rtpcodec.go

Exact match if fmtp parameters are not inconsistent.
e.g. default OPUS fmtp of the browsers are:
- Chrome:  `minptime=10;useinbandfec=1`
- Firefox: `maxplaybackrate=48000;stereo=1;useinbandfec=1`
They should be treated as matched.
#1711

Parse and compare FmtpLine on codec select

---

peerconnection.go
peerconnection_renegotiation_test.go
rtptransceiver.go

Which were previously unable to:
1. have a sending track set to them, or
2. receive a track after renegotiation.
I'm not 100% sure if this covers all cases where a track is added and
removed and then added again. BUT IIRC there was a change that did not
allow transceiver reuse after a track was removed from it. Again, not
100% sure.
Fixes #1722.

Fixes for pre-added recvonly transceivers

---

examples/rtp-to-webrtc/README.md
internal/mux/mux.go
internal/mux/mux_test.go
internal/mux/muxfunc.go

Before io.ErrShortBuffer and packetio.ErrTimeout would incorrectly end
the read loop. Now they are only printed.
Resolves #1720

Handle errors properly in mux readLoop

---

README.md
peerconnection.go
peerconnection_media_test.go
sdp.go

Use fine granularity lock to protect `rtpTransceivers` in  `PeerConnection` which shall make `AddTrack()` and `RemoveTrack()` thread-safe.
Fixes #1574
Note: 
- the added test `TestPeerConnection_RaceReplaceTrack` is from #1574
- not quite sure about the remaining `GetTransceivers()` callings in `peerconnection.go`; seems they are used as snapshots or cache, may still have data race in this PR.
- previously the coarse lock `mu` is used almost everywhere for exclusive access in `PeerConnection`; changing to a separated lock for `rtpTransceivers` might have implicit conflicts, which I'm not 100% sure by far.

PeerConnection: make AddTrack thread-safe

---

datachannel.go
sctptransport.go

`DataChannel.open` would panic during which if `PeerConnection` is closed,
stopping underlying `SCTPTransport` which sets association to `nil`;
`DataChannel.ensureSCTP` method doesn't guarantee `SCTPTransport`'s availability out of it's own scope.
Also fix similar issue in `SCTPTransport.Start`.
Fixes #1730

Fixes DataChannel panic on sctp transport race

---

datachannel.go
peerconnection_media_test.go
sctptransport.go

Use assocation() instead of accessing private struct member
member variable `association` in SCTPTransport renamed to `sctpAssociation`
This is a follow-up commit to #1747

SCTPTransport: add getAssociation

---

peerconnection.go

Potential deadlock:
In `CurrentLocalDescription()` or `PendingLocalDescription()`:
when gathering local candidates in `populateLocalCandidates()` (while holding PeerConnection lock),
agent would try submitting a task via `agent.run()`:
```go
a.chanTask <- task
```
the `chanTask` is consumed by `taskLoop` routine:
```go
for {
select {
case <-a.done:
return
case t := <-a.chanTask:
t.fn(a.context(), a)
close(t.done)
after()
}
}
```
while there're other routines using the agent, e.g. calling
`agent.updateConnectionState()`
```go
a.afterRun(func(ctx context.Context) {
a.chanState <- newState
})
```
and the submitted task would be run by the `after()` func in
`taskLoop()`, where the `a.chanState` is consumed by
`agent.startOnConnectionStateChangeRoutine()`
this `after()` task may block the …

Fixes peerconnection: potential deadlock

---

peerconnection.go

CurrentRemoteDescription and PendingRemoteDescription both access
members of the PeerConnection that should be protected by a lock.
Co-authored-by: Markus Tzoe <chou.marcus@gmail.com>

Hold lock when accessing remote description

---

examples/pion-to-pion/answer/Dockerfile
examples/pion-to-pion/docker-compose.yml
examples/pion-to-pion/offer/Dockerfile

1. Removes "host" network_mode 
Steps to reproduce:
$ cd examples/pion-to-pion
$ docker-compose up
ERROR: for answer  "host" network_mode is incompatible with port_bindings
2. Fix undefined os.ErrDeadlineExceeded
Steps to reproduce:
$ cd examples/pion-to-pion
$ docker-compose up
#4 13.95 pkg/mod/github.com/pion/ice/v2@v2.1.2/udp_mux.go:242:22: undefined: os.ErrDeadlineExceeded

Fix docker file

---

examples/ice-single-port/README.md
examples/ice-single-port/index.html
examples/ice-single-port/main.go
go.mod
go.sum
icemux.go

Demonstrate how using the new ICEUDPMux multiple PeerConnections
can be served via a single port.

Add examples/ice-single-port-mode

---

peerconnection.go
peerconnection_renegotiation_test.go
rtptransceiver.go

now proctected by lock:
- `CreateOffer`
- `CreateAnswer`
- `AddTransceiverFromKind`
- `AddTransceiverFromTrack`
newRTPTransceiver is no longer a PeerConnection method;
pc.`addRTPTransceiver` would fire `onNegotiationNeeded`;
pc.`AddTrack`, pc.`RemoveTrack` now hold lock for the entire function;

PeerConnection: more thread-safe

---

README.md
dtlstransport.go
settingengine.go

Adds option to the SettingEngine to override default SRTP protection profiles.
By default there are always two options enabled SRTP_AEAD_AES_128_GCM and SRTP_AES128_CM_HMAC_SHA1_80 and even when SRTP_AEAD_AES_128_GCM is first chrome will choose SRTP_AES128_CM_HMAC_SHA1_80. This options allows to force SRTP_AEAD_AES_128_GCM.

SRTP Protection Profiles in SettingEngine

---

rtpreceiver.go
rtpreceiver_go.go
rtpreceiver_go_test.go

See discussion with @OrlandoCo https://gophers.slack.com/archives/CAK2124AG/p1623504625397700
- RID is now set on remote tracks, if provided.
- Adds SetRTPParameters which can be used in ORTC to set codec information about the remote track.
I'm not sure if this is the best way to implement this, as the track will still miss the `id` and `streamID` + I'm not a big fan of adding public method for edge cases. 
Maybe it'd be better to  refacto `RTPReceiver.Receive()` to look more like `RTPSender.Send()`?

Implemented RTPReceiver SetRTPParameters for ORTC

---

peerconnection.go
peerconnection_go_test.go

In some rare cases during the ice connection stage change may result in deadlock. This fix makes iceConnectionState and connectionState atomic which should prevent deadlock.
Before this fix, some of the tests would randomly timeout, after this, I'm unable to reproduce the issue.
Also, I believe this is the same problem as described in https://github.com/pion/webrtc/issues/1809.
Fixes https://github.com/pion/webrtc/issues/1809

Fixed deadlock in peerconnection.go

---

constants.go
errors.go
peerconnection.go
rtpsender.go
rtpsender_test.go
track_remote.go

If the PayloadType changes for a SSRC update the codec on the
TrackRemote.
Resolves #1850

Support PayloadTypes changing a TrackRemote

---

pkg/media/h264reader/h264reader.go
pkg/media/h264reader/h264reader_test.go

There was a buffer overflow in H264Reader, it is now fixed.
Fixes #1734

Fix H264Reader buffer overflow

---

peerconnection.go
rtpsender.go
track_local.go

This PR fix `transceiver.Sender().Send()` not contain `HeaderExtensions` when `createStreamInfo`, the result is none of HeaderExtensions at interceptor.

Fix RTPSender's streamInfo miss headerExtensions

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Wrap around issue caused backup of packets in sample builder.
Fixes #1870

Fix: sample builder test always returns data

---

rtpreceiver.go

Modifications included in https://github.com/pion/webrtc/commit/f524fea32aadec9e1b6b06b886181ae67d32ea17 made https://github.com/pion/webrtc/pull/1831 useless:  when used in ORTC context, `tr` might stay `nil`, and a call to `getParameters` would result in a crash in that case.

Fix RTPReceiver getParameters

---

pkg/media/samplebuilder/sampleSequenceLocation.go
pkg/media/samplebuilder/sampleSequenceLocation_test.go

Before I decided that doing a full rewrite is the simpler option
I had started doing some cleanup on the code.  Although Galene has
now switched to a less broken samplebuilder, I guess I might as well
submit the bits I had already done.

Simplify sampleSequenceLocation

---

AUTHORS.txt
errors.go
rtpsender.go
rtpsender_test.go

When ReplaceTrack was set previously to nil it would be impossible to ReplaceTrack again with a non-nil value as r.track was set to nil.

Fixes ReplaceTrack

---

mediaengine.go

For using in SLI.
Requires https://github.com/pion/rtp/pull/142

Enable VP8 PictureID by default

---

peerconnection.go
rtptransceiver.go
sdp.go

Previously we've had a few if statements like `transceiver.Sender() != nil && transceiver.Sender().isNegotiated()` where during first condition `transceiver.Sender() != nil` would pass, but then in 2nd condition could become nil so `transceiver.Sender().isNegotiated()` would panic.
The original issue is only about `.Sender()` but II noticed the same problem with `.Receiver()` so I changed them too.
Fixes #1822

Fixes issue 1822

---

ortc_datachannel_test.go
ortc_media_test.go
ortc_test.go
rtpsender.go
rtpsender_test.go

Add public methods to allow set stream and track id, this is useful
when using ORTC API

Check for nil transceivers on get parameters

---

examples/play-from-disk-renegotation/main.go
examples/play-from-disk/README.md
examples/play-from-disk/main.go

time.Sleep is not precise, instead use a ticker.
Relates to golang/go#44343

Use time.Ticker in play-from-disk

---

errors.go
mediaengine_test.go
ortc_datachannel_test.go
peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
peerconnection_test.go
rtpreceiver_test.go
rtpsender_test.go
rtptransceiver_test.go
sdp.go

It isn't possible to send media if a MediaEngine has no codecs. This
catches a common misconfiguration issues that users find themselves in.
Resolves #1702

Throw error earlier for RTPSender with no codecs

---

AUTHORS.txt
icetransport.go
peerconnection.go
rtpreceiver.go
rtpsender.go
settingengine.go
track_remote.go

This gives an option to raise the receive MTU as SettingEngine option.
If SettingEngine has not been set the MTU, then default value is used instead, `1460`
https://github.com/pion/webrtc/issues/1925
Fixes #...

option to configure the receive MTU in SettingEngine option

---

examples/play-from-disk-renegotation/README.md
examples/play-from-disk/README.md

I've found that with the default ffmpeg configuration in the ivf-based `play-from-disk` examples, the bitrate is not specified. This results in a very poor default value of only 256 kbit/s which is low enough for the encoder to drop to black and white video on every third frames. When running the provided command, ffmpeg even warns us about this:
```
[libvpx @ 0000023541414040] Neither bitrate nor constrained quality specified, using default CRF of 32 and bitrate of 256kbit/sec
```
I believe this could lead some people to believe that this is an issue with their software or with Pion, when it's actually just a flag in ffmpeg. I don't understand why the ffmpeg authors set the defaults so low, but I've updated the README files so that the bitrate now matches that of the H264 stream from the …

Specify bitrate in ffmpeg commands for more usable video stream

---

go.mod
go.sum
pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Related to https://github.com/pion/rtp/pull/150 and https://github.com/pion/webrtc/pull/1882.
Also fixes a bug in the depacketizer: if there was no PartitionHeadChecker, the depacketizer would treat every packet as a potential partition head, even if it was at the beginning of the buffer.  Since I didn't want to tweak the tests to account for the fixed bug, I simply had the head checker return true if headBytes is nil.  Ideally, the tests should be fixed to do the right thing, which I have done in https://github.com/jech/depacketizer

Adapt the samplebuilder to the new version of the depacketizer.

---

AUTHORS.txt
constants.go
peerconnection.go
peerconnection_media_test.go
rtpreceiver.go
sdp.go
sdp_test.go

If we have a media section with no SSRC we would fire an OnTrack. This
code now properly ignores a MediaSection that has a rid attribute.
Resolves #1808

Don't consider simulcast for undeclared SSRC

---

atomicbool.go
peerconnection.go
peerconnection_go_test.go
rtptransceiver.go
sdp_test.go

Make RTPTransceiver Stopped an atomic
Add an accessor to make getting value easy. Also add
TestPeerConnection_SkipStoppedTransceiver. This commit also cleans
up RTPTransceiver creation. We used a helper function, when we should
have just used the provide constructor

Fixes RTPTransceiver: Stopped

---

srtp_writer_future.go

In RtpSender, if Read has been called and wait for srtpReady,
then if we call Close() immediately after
rtpSender.trasport.srtpReady, that means srtpWriterFuture's Close
may be called when it's init method is executing.
In Read -> init, goroutine may run at:
rtpWriteStream, err := srtpSession.OpenWriteStream()
if err != nil {
return err
}
s.rtcpReadStream.Store(rtcpReadStream)
s.rtpWriteStream.Store(rtpWriteStream)
In Close, goroutine may run at
if value := s.rtcpReadStream.Load(); value != nil {
return value.(*srtp.ReadStreamSRTCP).Close()
}
return nil
s.rtcpReadStream could be nil in the check at Close, so it
will not be closed.
And in Read method, the init method initiates the stream and
return. Then read at the stream's buffer, and blocked infinite
because the buffer is not closed. …

Fix RtpSender: may block infinite in Read

---

AUTHORS.txt
peerconnection_media_test.go
sctptransport.go

`(*SCTPTransport).generateAndSetDataChannelID` performed a double loop to find the next available data channel ID. This changes that behavior to generate a lookup map with the taken IDs first, so generating a data channel ID takes much less time.
Before, it would take more than 1000ms to generate the next data channel ID once you had roughly 50k of them. Now it only takes 4ms at that same point.
Fixes #1945
cc @coadler @kylecarbs

Fix double loop in data channel ID generation

---

constants.go
dtlstransport.go
errors.go
interceptor.go
peerconnection.go
peerconnection_media_test.go
rtpreceiver.go
rtpsender.go
rtptransceiver.go

Read + Discard packets from the Simulcast repair stream. When a
Simulcast stream is enabled the remote will send packets via the repair
stream for probing. We can't ignore these packets anymore because it
will cause gaps in the feedback reports
Resolves #1957

Handle Simulcast RepairStream

---

atomicbool.go
peerconnection.go
peerconnection_go_test.go
rtptransceiver.go
sdp_test.go

This reverts commit 6c3620093d714dfd7e25c9ba19e38df10af248b6.

Revert "Make RTPTransceiver Stopped an atomic"

---

peerconnection.go
rtpcodingparameters.go
rtpreceiver.go
sdp.go

Same issue with TWCC enabled as 11b887. We need to process the
RTX packets so that we can emit proper reports.

Handle non-Simulcast Repair Streams

---

AUTHORS.txt
go.mod
go.sum
peerconnection.go
sctptransport.go

A race existed with Negotiated DataChannels before this. Before
the remote could sends us a DataChannel message before the
datachannel was negotiated locally. We would then discard the
message and print an error.
This PR moves the processing of remote datachannel messages after
we have registered all local ones. It also informs
datachannel.Accept of existing datachannels in order to prevent
any initialization logic from proceeding incorrectly.

Open all DataChannels before accepting remote

---

peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go

if a transceiver is created by remote sdp, then set
prefer codec same as offer peer.
If a client set preference codec, then create offer and send to pion sfu,
then sfu create a recvonly transceiver from the sdp, but the codec seq
is the same as mediaengine's register, I think it should be same as the 
offer peer's prefer codec, so the client can use codec  prefer.
Fixes #...

Match remote codec ordering in transceivers created by remote SDP

---

AUTHORS.txt
atomicbool.go
peerconnection.go

Thanks for this awesome project. 
When I was learning the code, I realized the isClosed on Close function is not in atomic.
if this function is called at the same time on different go routines, the peerConnect may close multiple times.
Here is the fix to make the get and set in atomic.
Hope this help.

fix get set isClosed not in atomic

---

rtpsender.go
rtpsender_test.go

If a RTPSender doesn't have a track currently set and GetParameters is
called we would call a method on a nil pointer. Now instead of checking 
the Track kind we store the kind in the RTPSender.
Resolves #2065

Fix RTPSender.GetParameters crash

---

peerconnection.go
peerconnection_go_test.go

If SetRemoteDescription is called with offer SDP which has a=invalid,
PeerConnection sets its transceiver direction as recvonly when it has no transceiver yet.
Fix direction recvonly to invalid.
Fixes #2050

Set localdirection to inactive

---

peerconnection.go
rtptransceiver.go

in some case like session migration from one sfu node
to another, we need manual set mid of transceiver instead of
auto generate, to make mid consistent between to sfu node.
Fixes #...

Make setMid of Transceiver public

---

errors.go
rtpsender.go
rtpsender_test.go

If PeerConnection removes track while RTPSender is created and being negotiated,
RTPSender.Send would access nil pointer.
Check If track is nil.
I think it's related with issue #2065 
Fixes #...

Fix RTPSender.Send crash

---

mediaengine.go
mediaengine_test.go

This avoids a bug where negotiating Opus with PT 96 in an audio-only
session results in the VP8 codec being picked for a track (because
96 is the built-in type for VP8).
Rework `getCodecByPayload` to check negotiated audio types before
built-in video types, which avoids this issue. The code previously
would always check video types before audio types, even if audio
had already been negotiated.
Fixes https://github.com/pion/webrtc/issues/2080

Use audio negotiated PTs before video builtin PTs

---

rtpsender.go
rtpsender_test.go
track_local.go
track_local_static.go

This change makes it possible to set the RTP stream ID to
allow forwarding and production of simulcast streams.

Add ability to set RTP stream ID on TrackLocal

---

peerconnection.go
rtpreceiver.go
sdp.go

References - https://github.com/pion/webrtc/issues/2054
Do the set up of RTP receivers synchronously so that they
are ready to receive media as soon as signalling to remote
side is sent. Once signalling to remote side is sent, the
remote can send media at any time and receiver has to be ready.
Like the bug mentions, a negotiation quickly followed by
a renegotiation left the RTP receivers of the tracks in the
second offer not set up. If the tracks in the renegotiation
happen to be simulcast tracks, they are missed as browsers
send RID only in the first few packets.
The problem can be reproduced by introducing a 1 second
delay in Downstream direction in Network Link Conditioner
and using a modified version of LiveKit JS SDK sample app to
force a double negotiation spaced closely.
With this …

Set up RTP Receivers synchronously

---

peerconnection.go
sdp.go

If the SRTP Stream hasn't been opened yet we would attempt to process
(and fail) RTP traffic. This change causes us to not even attempt to
read.
No behavior change from this, but will cause less useless logging.

Ignore explicit SSRCes in RID Simulcast processing

---

peerconnection.go
peerconnection_go_test.go
sdp.go

When creating answer, check ICE role while determining DTLS role.
ORTC thread on how roles are set
https://github.com/w3c/ortc/issues/167#issuecomment-69409953
When remote is ice-lite and there is no answering role set,
the answer uses the default which is DTLS client. So 'setup'
is set as 'active' and answer sent.
But, when DTLS transport is started, it checks the ICE role
and sets itself as DTLS server (because remote is lite
and hence local agent becomes controlling ICE agent).
So, both sides end up being DTLS server adnd nobody sends
client hello.

Use ICE role to set DTLS role in answer

---

AUTHORS.txt
dtlstransport.go

In #2113 , we were seeing intermittent DTLS connectivity issues. Based on discussion with @Sean-Der and @kylecarbs in the thread, we suspected this condition in `dtlstransport` 
https://github.com/pion/webrtc/blob/8796a5c5a7359e12f0164823631d6e25579a4260/dtlstransport.go#L284-L286
It makes sense that we should be able to start a new DTLSTransport over an existing ICETransport, so this PR revises th e condition in `ensureICEConn` to allow `ICETransportStateNew`.
We're still testing - but potentially fixes #2113

fix: Allow ICETransportStateNew in ensureICEConn

---

errors.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
rtpsender.go
rtpsender_test.go
sdp.go
srtp_writer_future.go
track_local.go

@Sean-Der @davidzhao Not a real PR, but setting up one to get feedback on the direction. There are more bits to do here to make this simulcast capable, but wanted to make sure that the general approach is okay before I go further.
This makes sure that the API is not affected.
I was then planning to take encodings supplied in `RTPTransceiverInit` and apply it on the sender. Something like `setParamaters` on `RTPSender`. `setParameters` is much more strict. For v1 of this, I was thinking of not being that strict and apply the encodings. Then use that in `sdp.go` to generate the `simulcast:send` SDP. That will have both SSRC and RID, but I think that is fine.
And then I will have to figure out the `Read` and friends for the simulcast aware sender.

Support for send-side simulcast

---

pkg/media/h264reader/h264reader.go

optimize h.264 reader to reuse pre-allocated buffer during read buffer, and may reduce the chance of GC.
Fixes #...

optimize h.264 reader to reuse pre-allocated buffer during read

---

pkg/media/h264reader/h264reader.go
pkg/media/h264reader/h264reader_test.go

current h264reader will not return actual error, thus, as a user, I don't know error is caused by EOF, or socket close, or other failures. The fix will return the error to caller for debugging and troubleshooting
Fixes #...

return actual error during h264 stream read

---

track_local_static.go

The type assertion is not necessary, discovered by gocritic.

Remove unnecessary type assertion

---

gathering_complete_promise_example_test.go

It is not immediately obvious how to do traditional (non-trickle)
ICE in Pion, and the current documentation does not make it
sufficiently clear.  Add a testable example for non-Trickle ICE.

Add testable example for GatheringCompletePromise

---

sctptransport.go
settingengine.go
settingengine_test.go

Relates to pion/sctp#218
Current pion/sctp's receive buffer size is hardcoded as 1 MiB. This change makes the value configurable from the SettingEngine.
See pion/sctp#218 for more details about the context of this pull-request.

Max receive buffer size via SettingEngine

---

sdp.go
sdp_test.go

When running the reflect example against Firefox 99.0.1 I was receiving
errors around parsing the SDP from Pion.
The error was:
SIPCC Failed to parse SDP: SDP Parse Error on line 50:  c= connection
line not specified for every media level, validation failed.
According to the RFC [4566 5.7](https://datatracker.ietf.org/doc/html/rfc4566#section-5.7)
A session description MUST contain either at least one "c=" field in
each media description or a single "c=" field at the session level.
It MAY contain a single session-level "c=" field and additional "c="
field(s) per media description, in which case the per-media values
override the session-level settings for the respective media.
I don't see any errors in the Pion repos for this. Interestingly the
webrtc-rs project that is porting Pion to …

Resolve issue with rejecting tracks from Firefox

---

configuration_test.go
errors.go
icecredentialtype.go
icecredentialtype_test.go
iceserver.go
iceserver_test.go
peerconnection_js.go
peerconnection_js_test.go

When serializing to/from json, the ICECredentialType should serialize as as a string instead of an enumeration.

Add json serialization support to ICECredentialType

---

test-wasm/go_js_wasm_exec

Go starting with 680caf15355057ca84857a2a291b6f5c44e73329
split these into two files. Check if file exists so we can support both
versions

Use wasm_exec_node.js if exists

---

peerconnection_js.go

In 3.1.37, we removed the possibility for ICECredentialType
to be Unknown.  Remove remaining tests for this case from
the WASM code.

Remove occurrences of Unknonwn ICECredentialType

---

sctptransport.go

Fix the logic inverted by c1467e4
https://github.com/pion/webrtc/pull/2194/files#r870839078

Fix datachannel accept EOF check logic

---

mediaengine.go
mediaengine_test.go

First big thanks to @k0nserv who originally reported this and put together an initial test showing the failure.
This PR addresses an issue whereby under a specific (but not unusual) circumstance, pion fails in two different ways to generate the correct SDP extmap IDs for a track. Some browsers are more picky about this than others, but Firefox is known to be picky and this issue may be responsible for some reported incompatibilities.
Sequence to trigger the issue:
1. Pion side registers audio & video codecs and audio & video header extensions.
2. Pion side gets an audio-only offer from the remote, and responds with an answer.
3. At some later point in time, Pion side wants to add a video track and prepares a new offer.
4. Extmap IDs in the new offer SDP are usually incorrect (conflicting …

Fix incorrectly generated (i.e. conflicting or misassigned) extmap IDs when re-offering

---

AUTHORS.txt
icegatherer.go

It's possible for ICEGatherer to be closed after Gather had just started. We've seen this panic during load testing.

Fixed panic when ICEGatherer closed after calling Gather

---

mediaengine_test.go

This test previously assumed deterministic (i.e. ordered)
behaviour for getRTPParametersByKind which is not necessary, and
is no longer true following PR #2236 due to use of range. The
result was that occasionally this test would fail incorrectly
(thanks, golang-ci). This PR fixes the test.

Fix TestExtensionIdCollision

---

peerconnection.go
peerconnection_renegotiation_test.go
rtptransceiver.go

add currentDirection to RTPTransceiver, don't reuse transceiver if its currentDirection is sendrecv or sendonly
If remove track from transceiver then reuse it to add track without re-negotiation to transit its direction of sdp, then safari will not fire `removetrack` and `ontrack` events for that transceiver, so the mediatrack is lost.
Step:
1. sfu offer with 2 tracks, negotiation with safari, all things work, safari fire 2 `onTrack` event
2. sfu call RemoveTrack then AddTrack, will reuse rtptransceiver, after that, re-negotiation with safari. No new mid/transceiver in safari, the reused trasceiver changed its stream attributes to the new track.
3. safari can't fire `onTrack` for the new track.
According to https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-addtrack, if the transceiver …

Add currentDirection to RTPTransceiver

---

go.mod
go.sum
icegatherer.go
settingengine.go

When machine's network interface have more than one ip address and user don't want expose one of these ips to remote peer, interface filter can't work in this case, so add a ip filter for that

Add IPFilter to SettingEngine

---

peerconnection.go
peerconnection_renegotiation_test.go

Inside one cycle renegotiation, if user both has manually set Mid and auto generated Mid for transceivers, CreateOffer will failed for Mid conflict.

Fix generated Mid conflict with user set Mid

---

icegatherer.go
icegatherer_test.go

ICEGatherer throws panics in GetLocalCandidates(), GetLocalParameters() when it is already closed.
We have seen these panics during our load tests even though the PR #2230 has been merged.
This PR fixes these panics and added some test codes.
Fixes #2261 
Related to #2230

Fix panics in ICEGatherer when it is already closed

---

AUTHORS.txt
e2e/e2e_test.go
examples/broadcast/README.md
examples/broadcast/jsfiddle/demo.js
examples/data-channels/README.md
examples/data-channels/jsfiddle/demo.js
examples/insertable-streams/README.md
examples/insertable-streams/jsfiddle/demo.js
examples/play-from-disk/README.md
examples/play-from-disk/jsfiddle/demo.js
examples/reflect/README.md
examples/reflect/jsfiddle/demo.js
examples/rtcp-processing/README.md
examples/rtcp-processing/jsfiddle/demo.js
examples/rtp-forwarder/README.md
examples/rtp-forwarder/jsfiddle/demo.js
examples/save-to-disk/README.md
examples/save-to-disk/jsfiddle/demo.js
examples/simulcast/README.md
examples/simulcast/jsfiddle/demo.js
examples/swap-tracks/README.md
examples/swap-tracks/jsfiddle/demo.js

SetRemoteDescription accepts a RTCSessionDescriptionInit so this is no longer needed
Resolves #2324

Remove `new RTCSessionDescription` pattern

---

examples/ice-single-port/README.md

According to https://github.com/pion/webrtc/blob/045df4c4bfd47ae0d657af98053f18e9a707ac34/examples/ice-single-port/index.html#L48 and from running the example, it is clear there are actually 10 PeerConnections, not 5.  Also fixed some grammar.
Fixes #...

10 PeerConnections are made, not 5. Fix grammar.

---

AUTHORS.txt
examples/pion-to-pion/docker-compose.yml

Removed unnecessary properties from docker-compose file. **hostname** by default is equal to service name. Custom **container_name** and port mapping are also not needed for the example.

Simplify docker compose file of pion-to-pion

---

.github/workflows/examples-tests.yaml
examples/pion-to-pion/docker-compose.yml
examples/pion-to-pion/test.sh

Also add new GitHub Actions workflow to run tests for example apps
This is an implementation of the following idea: https://github.com/pion/webrtc/wiki/Big-Ideas#run-tests-against-examples
At the moment latest released example is tested. Next step is to build examples from source and test them.

Add test for pion-to-pion example

---

settingengine.go

Adjust formatting and grammar.
I did not check if the formatting is actually fixed.

docs: adjust `SetNAT1To1IPs` docstring

---

AUTHORS.txt
peerconnection_go_test.go
rtptransceiver.go

Today a remote `recvonly` transceiver can be satisfied by a `sendonly` or `sendrecv` transceiver. However a remote `sendonly` transceiver can only be satisfied by a `recvonly` transceiver.
This PR updates the answer handling code to be more consistent.

Make Transceiver Negotation more consistent

---

dtlstransport.go

Currently WriteRTCP function in `dtlstransport.go` doesn't return bytes written info. This PR fixes this and handles error and success response correctly. 
Fixes #...

fix: return correct bytes written on WriteRTCP on dtlsTransport

---

AUTHORS.txt
peerconnection.go
peerconnection_go_test.go
peerconnection_test.go

The peerconnection state should transit to connecting if icestate is checking or dtls connecting
Fixes #...

Fix peerconnetcion connecting state

---

peerconnection_renegotiation_test.go
peerconnection_test.go

Switch from reflect.DeepEqual to errors.Is

Fix lint errors in tests

---

datachannel.go
datachannel_go_test.go

Set cached values passed by SetBufferedAmountLowThreshold and OnBufferedAmountLow correctly when the underlying datachannel become open.
These method calls are ignored when they are called during OnDataChannel callback, before OnOpen callback.
* dc.SetBufferedAmountLowThreshold()
* dc.OnBufferedAmountLow()
The values are cached on webrtc.DataChannel object, but these were not passed when OnDataChannel is called.
Fixes #2441

Fix ignored calls during OnDataChannel

---

examples/data-channels-flow-control/main.go

Use bufferred channel (size 1) with select{} on write to avoid potential deadlock
* Fixed the datachannels-flow-control example code to avoid misdirecting users to a potential deadlock
* See #2439 for more details
Fixes #2439

Fix potential deadlock in the example

---

peerconnection.go
sdp.go

When there are more than one simulcast media sections in SDP, we need to check mid when parsing detail for the simulcast track.

Fix simulcast track set to incorrect stream id

---

peerconnection.go
peerconnection_media_test.go

Sending simulcast tracks from a pion sender to a pion receiver is failing unless there are other medias added:
```
Incoming unhandled RTP ssrc(xxxx), OnTrack will not be fired. single media section has an explicit SSRC
```
I admit I am not well versed in SDP semantics so please let me know if there's more to this that we should consider. The proposed changes are incredibly dumb as we are simply checking if there are multiple media sections and if not we avoid adding the ssrc attribute.
This is strictly related to https://github.com/pion/webrtc/pull/2299 which I guess is also a working solution although I am thinking that if we are being strict on the receiving side we should probably do the same on the sending side.

Avoid including SSRC in single media offers

---

datachannel.go
ortc_datachannel_test.go
peerconnection.go
sctptransport.go

When using ORTC API, the new accepted channel don't set the sctpTransport, see https://github.com/pion/webrtc/blob/master/sctptransport.go#L219.
it will panic if someone try to use it:
```
pair, err := channel.Transport().Transport().ICETransport().GetSelectedCandidatePair()
```

Fix ORTC accept datachannel sctpTransport is nil

---

settingengine.go

Just a small addition to the documentation of SettingEngine SetEphemeralUDPPortRange method, precising what are portMin and portMax effective default values.

SetEphemeralUDPPortRange documentation with values used by pion/ice

---

peerconnection.go

fix: glitch due to comment on the documentation

---

examples/rtp-to-webrtc/main.go

The default UDP buffer size on certain operating systems is too small (Windows 10/11 is ~32KB, Ubuntu 22.04 is ~208KB). This results in severe video freezing and packet-loss. This small feature increases the UDP receive buffer size to 300KB.
The main purpose of this is to make new users/developers aware that buffers may need to be increased on a case-by-case basis (since it isn't very well documented online).
Fixes #2496

Improvement to rtp-to-webrtc Example

---

icetransport.go
icetransport_test.go

Defined in w3c-peerconnection[0]
[0] https://www.w3.org/TR/webrtc/#dom-rtcicetransport-getlocalparameters

Add IceTransport.GetLocalParameters

---

examples/play-from-disk/README.md
examples/play-from-disk/main.go
examples/save-to-disk-av1/README.md
examples/save-to-disk/README.md
mediaengine.go

Resolves pion/rtp#190
Resolves pion/rtp#191

Add support to AV1 in `play-from-disk`

---

dtlstransport.go
settingengine.go

Add an option in the setting engine to log TLS key material when a DTLS connection is established with a peer. The option exists in pion/dtls but is not easily accessible. A user would use it very similarly to the crypto/tls package : 
```go
...
if keyLog := os.Getenv("SSLKEYLOGFILE"); len(keyLog) != 0 {
w, _ := os.OpenFile(keyLog, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0600)
settingEngine.SetDTLSKeyLogWriter(w)
}
...
```
This is somewhat related to #618 as it lets a user use Wireshark or a similar tools to capture and decrypt a particular session.

Add DTLS KeyLog configuration option in WebRTC API

---

rtpreceiver.go

Hi there! I want to use RTPTransceiver in on track func. RTP TRANSCEIVER is provided in the ON TRACK WEB API, but when I looked at it, it was difficult to access the RTP TRANSCEIVER in PION's ON_TRACK. I'm raising the PR because I would like to add a function to get the TR from the receiver rather than changing the supplied arguments of the ON_TRACK FUNC.
-   Add Transceiver func in rtp receiver
-   on_track api [https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/track_event](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/track_event)

Add RTPTransceiver func

---

pkg/media/media.go
pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

This option allows inspecting head packet for each media.Sample and then lets the user return their custom metadata. This might be useful in case when you need to check whether the given sample is a keyframe.

Adds WithPacketHeadHandler to SampleBuilder

---

AUTHORS.txt
rtpsender.go
track_local.go

This allows external users to provide their own TrackLocalContext to be
bound to a track.

Make TrackLocalContext an interface

---

mediaengine.go

It appears as though these two sets of lines are identical:
- https://github.com/pion/webrtc/blob/master/mediaengine.go#L137-L144
- https://github.com/pion/webrtc/blob/master/mediaengine.go#L164-L171
This PR removes the second set. Question: does order matter here? If so, in which order should the h.264 codec parameters be registered with the media engine?

Remove duplicate h.264 codec parameters from defaults

---

sctptransport.go
stats.go
stats_go_test.go

Adds functions to get SCTPTransport stats defined in https://www.w3.org/TR/webrtc-stats/#dom-rtcsctptransportstats. This PR is in conjunction with https://github.com/pion/sctp/pull/205.

Add SCTPTransportStats

---

peerconnection.go

one agent full, one lite: the full agent must take the controlling role, and the lite agent must take the controlled role

fix comments

---

dtlstransport.go
dtlstransport_test.go
internal/mux/endpoint.go
peerconnection.go
peerconnection_media_test.go
peerconnection_test.go

Resolves #1767
Resolves pion/dtls#151

Close PeerConnection on DTLS CloseNotify

---

peerconnection.go
rtpcodec.go
sdp.go
sdp_test.go

User report negotiation failed in https://github.com/livekit/livekit/issues/1850.
When the client sends offer to stop a transceiver (inactive), it removes the media section from group bundle, but pion still includes the media section in the answer, making negotiation failed by `Failed to set remote answer sdp: A BUNDLE group in answer contains a MID='3' that was not in the offered group`.

Generate answer to match group bundle in offer

---

peerconnection.go
peerconnection_renegotiation_test.go

I have encountered the following application panic with peerConnection using OnNegotiationNeeded handler:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x1677cea]
goroutine 1346 [running]:
github.com/pion/webrtc/v3.(*PeerConnection).checkNegotiationNeeded(0xc0006bb680)
/-S/vendor/github.com/pion/webrtc/v3/peerconnection.go:403 +0x16ca
github.com/pion/webrtc/v3.(*PeerConnection).negotiationNeededOp(0xc0006bb680)
/-S/vendor/github.com/pion/webrtc/v3/peerconnection.go:342 +0x10e
github.com/pion/webrtc/v3.(*operations).start(0xc0017fb398)
/-S/vendor/github.com/pion/webrtc/v3/operations.go:93 +0x63
created by github.com/pion/webrtc/v3.(*operations).Enqueue …
```

Fix checkNegotiationNeeded panic after ReplaceTrack(nil)

---

examples/data-channels-flow-control/main.go

At the current state of the code the deadlock is not achievable, but if `bufferedAmountLowThreshold` and `maxBufferedAmount` were to get changed up, it could happen.
Example: If `bufferedAmountLowThreshold = 1024`,
`maxBufferedAmount = 1280`, then if a message of len 999 is sent, `BufferedAmount()` could return `999`, and the condition would still evaluate to `true` (999 + 999 > 1280).
Since `bufferedAmountLowThreshold` was never exceeded, the `OnBufferedAmountLow` event would never fire, so we're stuck.
Related: #2474

docs: example: fix potential deadlock

---

datachannel.go
datachannel_js.go

This is in line with
* the docs for `BufferedAmountLowThreshold` ("When the bufferedAmount decreases from above this threshold to equal or below it")
* The actual code in `pion/sctp`: https://github.com/pion/sctp/blob/d6446e3b0d0495d9974e68fec9b7fdb79c018ca1/stream.go#L422
* The Web WebRTC spec: https://w3c.github.io/webrtc-pc/#event-datachannel-bufferedamountlow
This came up in [this discussion](https://gitlab.torproject.org/tpo/anti-censorship/pluggable-transports/snowflake/-/merge_requests/144#note_2903094).
Related: #2473.

Docs: correct `OnBufferedAmountLow` condition

---

interceptor.go

Updates pion/interceptor and pion/rtcp and adds a helper function to register an interceptor that produces congestion control feedback as defined in [RFC 8888](https://datatracker.ietf.org/doc/rfc8888/).

Add helper to configure CCFB (defined in RFC 8888)

---

examples/simulcast/main.go
interceptor.go
mediaengine_test.go
peerconnection.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
rtpreceiver_go_test.go

Enable Simulcast RTP Headers by default

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Refs #2323
Co-authored-by: Juliusz Chroboczek <jch@irif.fr>

Samplebuilder: add tests for padding packets

---

datachannel.go

The two variables used here are protected by the mutex `mu` they should only be accessed when the lock is held. 
https://github.com/pion/webrtc/issues/2586

fix race in datachannel handleOpen

---

AUTHORS.txt
rtpreceiver.go
track_remote.go

When the TrackRemote.Read reads a rtx packet from the channel and copying the data from the buffer, the buffer can be written by the goroutine of receiveForRTX at the same time, use a buffer pool to fix it.

Fix data race of RTX packet

---

constants.go
rtpreceiver.go

My earlier PR #2592 added support for distinct-SSRC RTX packets, returning RTX packet info in the attributes. But, the constants for the attribute names (which should be part of the public API) were erroneously made private due to a typo. This fixes that.

RTX attribute constants should be public

---

rtpsender.go

This PR addresses an issue where calling `RTPSender.ReplaceTrack` with a nil parameter on a sender with more than 1 encoding (simulcast) would only cause the 1st encoding to be unbound, breaking common publisher reconnection workflows with simulcast enabled.

ReplaceTrack resets all track encodings

---

api.go
track_local_static_test.go
vnet_test.go

As discussed on Discord with @Sean-Der, `NewAPI()` should register default codecs and interceptors unless configured otherwise.

NewAPI: register default codecs and interceptors

---

constants.go
sdp.go
sdp_test.go

If the publisher sends an offer with paused simulcast stream like `a=simucalst:send 1;~2;~3`, the sfu needs to respond with paused stream too, otherwise, it will make the publisher's inactive encoding to become active unintentionally.
Fixes #...

Answer to paused simucalst stream correctly

---

peerconnection.go
peerconnection_media_test.go
rtpreceiver.go
rtptransceiver.go

Skip padding packet for simulcast probe
Fix rtx attributes panic for nil map

Skip padding packet for simulcast probe

---

mediaengine.go
mediaengine_test.go
peerconnection.go
sdp.go

Always handle header extensions from packet read
from interceptor, let interceptor has consistent
chance to process headers
Fix rtx is not negotiated when there is multiple
codecs has same mime but different profile (H264)
Fix rtx stream info missed when SSRC group attr
shows after base track's ssrc attr.

Refine rtx support

---

constants.go
mediaengine.go
mediaengine_test.go
peerconnection.go
rtpreceiver.go
sdp.go
track_remote.go

RTX support for v3

---

dtlstransport.go
rtpsender.go

Fixes interceptor.RTCPReaderFunc typo
Although interceptor.RTCPReaderFunc and interceptor.RTPReaderFunc have the same signature, at interceptor.BindRTCPReader should use interceptor.RTCPReaderFunc

Fix interceptor.RTCPReaderFunc typo

---

pkg/media/media.go
pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

To get RTP extension data associated with the sample.

SampleBuilder: Return header of sample's head packet

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Flush marks all valid samples in the buffer to be popped. Useful for graceful shutdown without losing buffered data as much as possible.

SampleBuilder: Add Flush method

---

pkg/media/media.go
pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Replaces https://github.com/pion/webrtc/pull/2681 which returned only a head packet's header.
When the option WithRTPHeaders is set, SampleBuilder returns RTP headers of the packets forming the sample as Sample.RTPHeaders.
This feature is useful for getting RTP extension data associated with the sample
Lint job is failing due to https://github.com/pion/.goassets/issues/201
- https://github.com/pion/webrtc/pull/2681#issuecomment-1970625842

SampleBuilder: Add option to return RTPHeaders

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Sample returned by `Pop()` contains `PacketTimestamp` field now, so `PopWithTimestamp()` is redundant.
As we're now preparing v4, it's good time to remove it.
---
Use Sample.PacketTimestamp field instead.
Migration example:
```diff
- sample, timestamp := s.PopWithTimestamp()
+ sample := s.Pop()
+ timestamp := sample.PacketTimestamp
```
---
SampleBuilder: Remove WithPartitionHeadChecker
Deprecated by https://github.com/pion/webrtc/pull/1928

SampleBuilder: Remove deprecated functions

---

datachannel.go
datachannel_go_test.go
peerconnection.go
sctptransport.go
sctptransport_test.go

This allows users of detached datachannels to garbage collect resources associated with the datachannel and the sctp stream. There is no functional change here.
Fixes #2672

Drop reference to detached datachannels

---

go.mod
go.sum
icegatherer.go
settingengine.go

Relates to https://github.com/pion/webrtc/issues/2668
Fixes #2668

Expose stunGatherTimeout config from ice pkg

---

examples/ice-restart/README.md
examples/whip-whep/main.go
pkg/media/rtpdump/rtpdump.go
pkg/media/samplebuilder/samplebuilder_test.go

chore: fix some typos

---

track_local_static.go
track_local_static_test.go

To add padding-only samples call GeneratePadding
v4 version of https://github.com/pion/webrtc/pull/2745

Add padding support to TrackLocalStaticSample

---

examples/simulcast/main.go

Fix one of the layers can't send back video because the transceiver is used for receiving.
Fixes #...

Add recvonly transceiver for simulcast sample

---

peerconnection_media_test.go
rtpreceiver.go
track_remote.go

Fix #2751, updates remote track's rtx ssrc for
simulcast track doesn't contain rtx ssrc in sdp
since readRTX relies on rtx ssrc to determine if
it has a rtx stream.
Fixes #...

Update RtxSSRC for simulcast track remote

---

interceptor.go
peerconnection_media_test.go

Newly added test could not pass as simulcast extension headers are not enabled by default on v3

fix TestPeerConnection_Simulcast_RTX on v3

---

peerconnection_media_test.go
track_remote.go

Backport of 8e1b9745104bca3bf1beddfe2511d655512dadfe

Properly update metadata when PayloadType is 0

---

peerconnection.go
peerconnection_go_test.go

- Fixes #2774
Prior to this change, when `OnNegotiationNeeded` was not set before negotiation needed causing events were added to the op queue, there's a chance (based on ordering of goroutines) that the `negotiationNeededState` will get stuck in `negotiationNeededStateQueue`. This is kind of a consequence of breaking the canon, but this fix and test appear to be fine.

Reset state machine after negotiationNeededOp

---

peerconnection_media_test.go

Fix race condition in test

---

datachannel.go
peerconnection.go
peerconnection_close_test.go

This ensures no goroutines are running when a PeerConnection is closed. I'd also like to backport this into v3 so that existing users can benefit. Relies on https://github.com/pion/ice/pull/706 (tests will fail before that's in).

Make pc.Close wait on spawned goroutines to close

---

datachannel.go
peerconnection.go
peerconnection_close_test.go
peerconnection_go_test.go

Don't block Close on spawned goroutines

Revert 7c8bfbd44a and add test

---

mediaengine.go
mediaengine_test.go
peerconnection.go
peerconnection_media_test.go
sdp.go

We noticed that once pion has negotiated headers and codecs for a given Kind, when a subsequent offer SDP adds a media section for that same Kind with different header extensions, the generated answer uses the original headers for all media sections. 
This doesn't happen in Chrome, which never seems to send mixed headers like this. Firefox does, though.
We ran into this when sending an offer in which the first video media section had simulcast disabled, and thus didn't set this attribute
```
a=extmap:8/sendonly urn:ietf:params:rtp-hdrext:sdes:rtp-stream-id
```
but the second video media section had simulcast enabled, so included that header.
The resulting answer didn't include that header in either media section, but the second media section did correctly have these attributes 
``` …
```

Match header extensions to all media sections in offer

---

peerconnection.go

This prevents a race with `checkNegotiationNeeded` that inspects attributes of the SDP's MediaDescriptions. It's a hard to reproduce race but it has happened.

Hold pc.mu while populating local candidates

---

dtlstransport.go

Added support for SRTP_NULL_HMAC_SHA1_80 protection profile (cipher). It is disabled by default. You need to use SettingEngine and set list of allowed SRTP protection profiles using its SetSRTPProtectionProfiles function called with dtls.SRTP_NULL_HMAC_SHA1_80 as a parameter. You need to do this for both pion peers. For non-pion ones you may need to enable it somewhere too, as NULL cipher is usually disabled for security reasons.
Fixes #2273

Added support for SRTP_NULL_HMAC_SHA1_80 cipher

---

interceptor_test.go
peerconnection.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
rtpreceiver.go

libwebrtc has started sending media probes on an unannounced SSRC(0). This adds a special case to accept SSRC 0 and Read the RTP packets. This causes the TWCC reports to properly be generated.

Properly handle non-media probes

---

dtlstransport.go

Added support for SRTP_NULL_HMAC_SHA1_80 protection profile (cipher). It is disabled by default. You need to use SettingEngine and set list of allowed SRTP protection profiles using its SetSRTPProtectionProfiles function called with dtls.SRTP_NULL_HMAC_SHA1_80 as a parameter. You need to do this for both pion peers. For non-pion ones you may need to enable it somewhere too, as NULL cipher is usually disabled for security reasons.

Added support for SRTP_NULL_HMAC_SHA1_80 cipher (v3 CP)

---

dtlstransport.go
peerconnection.go

handleIncomingSSRC will call streamsForSSRC which opens rtp/rtcp streams that if unhandled can be leaked resources. Now we will proactively open them before calling handleIncomingSSRC and close then later. In the future it would be better to do this inside handleIncomingSSRC to protect other callers.

Close unhandled rtcp simulcast streams

---

rtpreceiver.go

Fix #2830. The TrackRemote.Read could block in
readRTP if the buffer is empty then rtx packets
arrival before next media rtp packet will be
readed after the next media rtp packet and cause
out-of-order fb and mess up remote peer's
bandwidth estimation.

Fix our-of-order twcc fb cause by rtx blocked

---

examples/insertable-streams/main.go

Hello, 
While looking at the WebRTC examples, I came across the following comment in the "play-from-disk" example:
(line 196-198)
```
// It is important to use a time.Ticker instead of time.Sleep because
// * avoids accumulating skew, just calling time.Sleep didn't compensate for the time spent parsing the data
// * works around latency issues with Sleep (see https://github.com/golang/go/issues/44343)
```
However, the "insertable streams" example still uses time.Sleep. I changed the code of the example to use time.Ticker like the "play-from-disk" example.
Fixes #2835

Change time.Sleep to time.Ticker in insertable streams example

---

peerconnection.go
sdp.go
sdp_test.go

Map iteration order is not guaranteed by Go, so it's an error to iterate over a map in places where maintaining the same ordering is important.
This change replaces the map of simulcastRid{} with an array of the same type. The simulcastRid{} type is extended to hold the rid-id which previously was used as the key in the map.
Accesses to the map are replaced with range loops to find the desired rid-id for each case.
Default code format applied.
Unit tests passed.
Fixes #2838

RID order guaranteed by avoiding iteration over a map

---

examples/bandwidth-estimation-from-disk/main.go
examples/data-channels-detach/jsfiddle/main.go
examples/data-channels-detach/main.go
examples/data-channels-flow-control/main.go
examples/data-channels/main.go
examples/insertable-streams/main.go
examples/ortc-media/main.go
examples/ortc/main.go
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go
examples/play-from-disk-renegotiation/main.go
examples/play-from-disk/main.go
examples/simulcast/main.go
interceptor_test.go
peerconnection_media_test.go

In Go 1.22 and earlier, a ticker needs to be explicitly stopped
when it's no longer useful in order to avoid a resource leak.
In Go 1.23 and earlier, an orphaned ticker will eventually be
garbage collected, but it's still more thrifty to stop it early.
Supersedes #2839.

Avoid leaking tickers

---

internal/mux/mux.go
internal/mux/mux_test.go

As discussed in [this](https://gophers.slack.com/archives/CAK2124AG/p1703996245888079) thread on the Gophers Slack, internal/mux needs a pending queue for packets that would dropped in some situations. (e.g. ICE transport blocks until it is in a connected state, losing any DTLS packets received in the meantime)
Sorry, I accidentally closed the issue before. I've reopened an issue with fixes.
N/A

Avoid dropping packets immediately in mux

---

pkg/media/ivfwriter/ivfwriter.go
pkg/media/ivfwriter/ivfwriter_test.go

This PR fixes the incorrect header timestamp written into the frame headers.
Fixes #2384

Fix: IVF writer writing invalid timestamp value into frame headers

---

datachannel.go
go.mod
go.sum
icegatherer.go
icetransport.go
internal/mux/mux.go
operations.go
operations_test.go
peerconnection.go
peerconnection_close_test.go

v3: Add PeerConnection.GracefulClose

---

sctptransport_test.go

We need to close both the ends here for all the goroutines to complete. 
The corresponding commit in v3 is here: https://github.com/pion/webrtc/pull/2861/commits/484d89ad38ea47a460fd86db2351823622897932

Fix SCTPTransport OnClose test

---

examples/simulcast/main.go
examples/swap-tracks/main.go

Refs https://github.com/pion/example-webrtc-applications/pull/228

Only send PLIs for video tracks in examples

---

dtlstransport.go
settingengine.go
settingengine_test.go

Extend the SettingEngine to expose the DTLS handshakes hooks added in https://github.com/pion/dtls/pull/631

Add DTLS handshake hooks to SettingEngine

---

peerconnection.go
peerconnection_close_test.go

@dgottlieb found an issue in the wild where if concurrent GracefulCloses happen, my wonky atomic bool logic could go awry and cause a leak of sorts and no actual graceful closure. I took some time to clean up the naming and comments in this code while working on the fix which is mainly to wrap a lock around the two bool operations, but also to have a more stringent series of operations when Graceful and normal close are overlapping.

Fix concurrent pc.GracefulClose

---

examples/stats/README.md
examples/stats/main.go

Add PeerConnection.GetStats() call with a Type Switch

Improve examples/stats

---

peerconnection.go
peerconnection_renegotiation_test.go

Should not reuse transceiver (remove & add track) in one round negotiation, it causes the transceiver change ssrc/msid without transit to inactive and the remote peer connection can't fire track close and OnTrack event.
Failure case:
1. pcOffer,pcAnswer negotiate a track A with direction `SendRecv`, `RecvOny`
2. offer = pcOffer.CreateOffer, send to pcAnswer, 
3. pcAnswer.SetRemoteDescription(offer), CreateAnwser, SetLocalDescription
4. pcOffer.RemoveTrack(A), SetRemoteDescription(answer)
5. pcOffer.AddTrack(B), offer2 =  CreateOffer
In step 5, B should not reuse track A's transceiver, otherwise the transceiver in offer and offer2 will not change direction but has different ssrc, cause pcAnwser can't fire OnTrack correctly.
Fixes #...

Don't reuse transceiver in one round negotiation

---

internal/mux/mux.go

This removes warning logs like:
```
Warning: mux: no endpoint for packet starting with 21
```
when closing the connection. 
Replace RWMutex with Mutex because there's only 1 goroutine reading.

Reduce Mux logging on Close

---

icetransport.go

Returning the object with stat id is useful when cross-referencing stats.

Return object icluding stat id for selected pair

---

sctptransport.go

the association should send the abort message before before changing the state to closed and closing the association as defined by the webrtc spec in step 6 
https://www.w3.org/TR/webrtc/#dom-rtcpeerconnection-close
When the peerConnection is closed without sending an abort message, it cause the other peer to hang on it's connection until it face a timeout or other kind of event showing that the connection is closed
This can be an issue with device who can only do a few concurrent stream
This was tested with real cameras and instead of the connection hanging for 30 seconds, it closed immediately

add Abort function to sctptransport

---

sdp.go

Pion extracts them from ssrc-group line so this didn't failed Pion<->Pion. Chrome/FireFox uses the dedicated a=ssrc lines and our Offer/Answer would break negotation
Fixes #2922

Add missing a=ssrc lines for RTX/FEC

---

peerconnection.go
settingengine.go
settingengine_test.go

This will allow getting OnTrack events before RTP packets are received (non-simulcast)

Add SetFireOnTrackBeforeFirstRTP

---

track_local_static.go
track_local_static_test.go

Allow media engine to register custom payloader depending on the mime type
Fixes #2928

feat: allow media engine to register custom payloader on mimetype

---

peerconnection_go_test.go

Test that NULL Protection Profile is disabled

---

icetransport.go

Struct member is copied to stack already, `stop` just incorrectly was referencing the member.
Found in CI

Fix race when closing ICE Transport

---

settingengine.go

This should it easier to understand whether you're supposed to return `true` or `false`.
I know it's pretty much the standard that `true` is for `keep`, but this is a simple change that should make developers think less.
The same change probably should be implemented for pion/ice, where these functions are actually invoked.
No

refactor: clarify filter func return val meaning

---

peerconnection.go
settingengine.go
settingengine_test.go

Close peerconnection on DTLS.CloseNotify
could break ice restart with dtls restart,
when the dtls finger-print changed, the
browser could teardown the old dtlstransport
and establish new one then pion could close
the peerconnection and restart failed. So
browser don't do this and spec also don't
say peerconnection should close when dtls
is closed.
Remove this feature might break applications 
already relies on this behavior for quick close 
so add a SettingEngine option to disable it. 
Fixes #...

Add option to disable close by dtls

---

datachannel.go

It wasn't clear (at least to me)
what "idiomatic API" it's referring to.
But, judging from the `data-channels-detach` example comments,
this is what it's made for.
https://github.com/pion/webrtc/blob/f29ef99b220beb906c60e7f1aebac6c02498daf9/examples/data-channels-detach/main.go#L4
None.

Improve `DataChannel.Detach()` docstring

---

mediaengine.go
mediaengine_test.go
rtpcodec.go
rtptransceiver.go

Update MediaEngine codec creation to take into account remote and local rtcp-fb. Before we would incorrectly always take the remote rtcp-fb and ignore local.
Resolves #2943
Resolves #2944
Resolves #1968

Use local+remote codecs to generate RTCP Feedback

---

peerconnection.go

Please do not commit until @Sean-Der has had a chance to comment on 2943.
Fixes #2943

Improve the documentation of NewPeerConnection

---

peerconnection.go
rtptransceiver.go

There is use of `t.stopped` in `peerconnection.go`, but that flag is not set/used in `RTPTransceiver` at all. This PR sets that when a transceiver is stopped and provides an API to check if a transceiver is stopped.
@Sean-Der @davidzhao @cnderrauber The fact that code does not seem to get tripped makes me think I am missing something, but I noticed the ☝️ (i. e. `stopped` flag in `RTPTransceiver` was not set/used) and made this PR to address this. Have tested this change with LiveKit and it seems fine.

Populate RTPTransceiver stopped flag

---

mediaengine.go
mediaengine_test.go
rtpcodec.go
rtptransceiver.go

Backport of #2972 into v3.
Tested to TTRT in Galene, thanks a lot Sean.

Backport #2972 to v3

---

sctptransport.go
sctptransport_test.go

https://github.com/pion/webrtc/pull/2696 introduced removing datachannels from the sctptransport for better garbage collection.
That PR introduced a race condition for data channels created before connection establishment. When an out of band negotiated data channel, created before peerconnection establishment is detached, there's a race between the data channel being removed from `r.dataChannels` and it being copied in to the existing data channel slice in the acceptDataChannels goroutine.
This PR fixes this race by copying the slice before any datachannels could be detached.

Fix detached datachannels handling

---

interceptor_test.go
peerconnection.go

The following panic was encountered in the [stats interceptor](https://github.com/pion/interceptor/tree/master/pkg/stats):
```
panic: sync: WaitGroup is reused before previous Wait has returned
sync.(*WaitGroup).Wait(0xc08227bce0?)
go/_std_1.22/src/sync/waitgroup.go:118 +0x74
github.com/pion/interceptor/pkg/stats.(*Interceptor).Close(0xc08ff1de20?)
github.com/pion/interceptor.(*Chain).Close(0xc0423bbb90?)
github.com/pion/webrtc/v4.(*PeerConnection).close(0xc0423bbb80, 0x0)
github.com/pion/webrtc/v4.(*PeerConnection).Close(...)
github.com/pion/webrtc/v4.(*PeerConnection).startTransports.func1.1()
```
It occurs because [wg.Add](https://github.com/pion/interceptor/blob/master/pkg/stats/interceptor.go#L133) is called after [wg.Wait](https://github.com/pion/interceptor/blob/master/pkg/stats/int …

Close interceptor after PeerConnection is closed

---

stats.go
stats_go_test.go

According to w3c:
https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats-encoderimplementation
https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-decoderimplementation

Add Encoder/Decoder info to stats

---

examples/bandwidth-estimation-from-disk/main.go

fix examples/bandwidth-estimation-from-disk

---

interceptor_test.go

End-to-end test for the NACK sending interceptor.  It notably tests negotiation.  See the function comment for details.

Add an end-to-end test for the NACK sender.

---

pkg/media/ivfreader/ivfreader.go
pkg/media/ivfwriter/ivfwriter.go
pkg/media/ivfwriter/ivfwriter_test.go

IVFwriter produces incorrect timestamps leading to unplayable video with the changes introduced in https://github.com/pion/webrtc/pull/2853.
The confusion lies in the different timestamps.
The RTP timestamp refects the sampling clock for the media stream. This timestamp increments based on the sampling rate.
The PTS of a media stream represents the presentation time in the time base units.
v3 first captured packets from examples/save-to-disk (`ffprobe -select_streams v -show_packets -show_entries packet=pts,pts_time,dts,dts_time,duration,duration_time,size,pos -of default output.ivf`)
```
[PACKET]
pts=0
pts_time=0.000000
dts=0
dts_time=0.000000
duration=1
duration_time=0.033333
size=2749
pos=32
[/PACKET]
[PACKET]
pts=1
pts_time=0.033333
dts=1
dts_time=0.033333
duration=1 …
```

Fix ivf timestamps

---

datachannel.go
datachannel_go_test.go

This PR fixes an issue where calling `dataChannel.Close` on 'connecting' state channels didn't work as expected; It adds the ability to reject data channels directly from the `OnDataConnection` handler.
Fixes https://github.com/pion/webrtc/issues/2659

Gracefully close connecting channels

---

stats.go
stats_go_test.go

According to w3c:
InboundRTPStreamStats:
- https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-pausecount
- https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalpausesduration
- https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-freezecount
- https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-totalfreezesduration
- https://www.w3.org/TR/webrtc-stats/#dom-rtcinboundrtpstreamstats-powerefficientdecoder
OutboundRTPStreamStats:
- https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats-powerefficientencoder
- https://www.w3.org/TR/webrtc-stats/#dom-rtcoutboundrtpstreamstats-scalabilitymode

Extended stats metrics

---

interceptor_test.go

One variable was misnamed, and we never checked for the end
of the RTCP loop.

Minor fixes to TestInterceptorNack

---

interceptor.go

Mention that is must be called after registering codecs.

Improve documentation of ConfigureTWCCSender

---

pkg/media/ivfwriter/ivfwriter.go

[RFC 6386](https://www.rfc-editor.org/rfc/rfc6386#section-9.1) describes the least significant bit of the first byte of the header as:
```
A 1-bit frame type (0 for key frames, 1 for interframes).
```
The change is functionally a no-op, but the naming implies the wrong logic (you would assume `isKeyFrame == 1` means it is a key frame, but the opposite is true).
Fixes #...

Rewrite VP8 isKeyFrame check

---

datachannel.go
datachannel_go_test.go

This fixes a regression bug introduced in commit https://github.com/pion/webrtc/commit/835ac3b08ef5dfd0f6c0b047cdeea635258a21e3, where this line was removed: https://github.com/pion/webrtc/commit/835ac3b08ef5dfd0f6c0b047cdeea635258a21e3#diff-b8da7f3e746d55a2fe2a4295ae5fe5cf76b9512d7665201285143e25ab3bd3b9L423.
Related issue https://github.com/pion/webrtc/issues/3005

Fix deadlock in DataChannel with mutex unlock

---

mediaengine.go

The removed comment predates the introduction of locks in the RegisterCodec method.

Remove outdated safety comment in RegisterCodec

---

icecandidate.go
icecandidate_test.go

Ensure that ICE candidates are retained when parsed and stringified, and converted back to ICE.candidate.
required ICE PR https://github.com/pion/ice/pull/758 and https://github.com/pion/ice/pull/759
Partly solves  https://github.com/pion/webrtc/issues/2993

Preserve ICE candidate Extensions

---

pkg/media/h264writer/h264writer.go
pkg/media/h264writer/h264writer_test.go

Before we would call Write even if no bytes were available.

Fix H264Writer writing 0 length payloads

---

peerconnection_renegotiation_test.go
rtpreceiver.go
rtpreceiver_go_test.go

Add a nil rtpinterceptor check before invoking read method
Fixes #2929

fix: rtcp interceptor nil panic

---

internal/fmtp/fmtp.go
internal/fmtp/fmtp_test.go
mediaengine.go
rtpcodec.go

In pion/webrtc, currently codecs are matched regardless of the clock rate and the channel count, and this makes impossible to fully support codecs that might have a clock rate or channel count different than the default one, in particular LPCM, PCMU, PCMA and multiopus (the last one is a custom Opus variant present in the Chrome source code to support multichannel Opus).
For instance, let's suppose a peer (receiver) wants to receive an audio track encoded with LPCM, 48khz sample rate and 2 channels. This receiver doesn't know the audio codec yet, therefore it advertises all supported sample rates in the SDP:
```
LPCM/44100
LPCM/48000
LPCM/44100/2
LPCM/48000/2
```
The other peer (sender) receives the SDP, but since the clock rate and channel count are not taken into consideration when …

Fix matching codecs with different rate or channels

---

icetransport.go
icetransport_test.go

Exists in webrtc-pc, we just haven't implemented it yet

Add GetRemoteParameters to ICETransport

---

mediaengine.go
mediaengine_test.go
rtptransceiver_test.go
sdp_test.go

This PR adds changes to return an error if the codec already exists on the codecs list. This way now the implementing party should take care of duplicate codecs addition if the payload type is the same.
Fixes #3015

Fix addCodec to return error if payload type exists in codecs list

---

errors.go
mediaengine.go

Move ErrCodecAlreadyRegistered to errors.go
Chore Cleanup after this PR https://github.com/pion/webrtc/pull/3016

Move ErrCodecAlreadyRegistered to errors.go

---

examples/save-to-disk-av1/README.md
examples/save-to-disk/README.md
examples/save-to-disk/jsfiddle/demo.js

Fix a bug where the session description would be displayed if the media permission was resolved instantly.
Fix the jsfiddle for save to AV1 example example: do not request audio.

Fix save to disk examples

---

examples/play-from-disk-renegotiation/README.md
examples/play-from-disk-renegotiation/main.go

Add support for AV1 and VP9 to play-from-disk-renegotiation example
Fixes a bug where it misses few packets at the start.
part of the AV1 enhancement overall https://github.com/pion/webrtc/issues/3036

Add support for AV1 and VP9 to play-from-disk-renegotiation example

---

errors.go
peerconnection.go
peerconnection_media_test.go

Introduces a fallback mechanism to handle undeclared SSRCs from multiple sections using the RTP stream's payload type. For legacy clients without MID extension support, it documents the existing behavior for handling undeclared SSRCs in single media sections.
This matches the behavior with chrome and Firefox. https://chromium.googlesource.com/external/webrtc/+/refs/heads/master/call/rtp_demuxer.cc#372
resolves #3065

Resolve undeclared SSRC using the payload type

---

.golangci.yml
api_test.go
datachannel_go_test.go
datachannel_test.go
dtlsrole_test.go
dtlstransport_test.go
icecandidate_test.go
icecandidateinit_test.go
icecandidatetype_test.go
icegatherer_test.go
iceprotocol_test.go
icetransport_test.go
interceptor_test.go
internal/fmtp/fmtp_test.go
internal/util/util_test.go
networktype_test.go
peerconnection_close_test.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
peerconnection_test.go
pkg/media/rtpdump/reader_test.go
pkg/media/rtpdump/rtpdump_test.go
pkg/media/rtpdump/writer_test.go
pkg/media/samplebuilder/samplebuilder_test.go
rtpsender_test.go
sctptransport_test.go
sdp_test.go
settingengine_test.go
stats_go_test.go

Use testify's assert package instead of the standard library's testing package.
https://github.com/pion/.goassets/pull/222

Update lint rules, force testify/assert for tests

---

examples/pion-to-pion/README.md

This PR updates the pion-to-pion example README to include `@latest`, aligning it with other examples.
To install the module without being inside the WebRTC repository, explicitly specifying the version is required.
For reference, see other examples, e.g., [reflect example](https://github.com/amanakin/webrtc/tree/master/examples/reflect).

Fix pion2pion example readme

---

peerconnection.go

My tests executed with race detector enabled found that code tries to read value of `pc.sctpTransport.dataChannelsRequested` without lock.

Added missing lock

---

sctptransport.go

It simplifies tracking amount of unsent data for all data channels, including ones in closing state. Especially useful for IoT apps which use multiple data channels and have to monitor memory usage.

Added SCTPTransport.BufferedAmount

---

mediaengine.go
mediaengine_test.go
peerconnection.go
settingengine.go

This extends PR #2632 and Adds the capability to have multi-codec negotiation just by setting a flag in the media engine.
Fixes #...

Add multi codec negotiation feature

---

track_local_static.go
track_local_static_test.go

Move to the new RTP API newPacketizerWithOptions, add WithRTPTimestamp To make it possible to set the initial RTP timestamp for the track.
Fixes https://github.com/pion/rtp/issues/111

Add WithRTPTimestamp to set  initial RTP timestamp

---

peerconnection.go
peerconnection_go_test.go

Return an error if a candidate with a username fragment that does not match the username fragment in the remote description is added. This usually indicates that the candidate was generated before the renegotiation.
Last time I tested Chrome silently drops such candidates, firefox returns an error.
Maybe we should also handle "generation" extension.
Fixes #2993 
Fixes #2511

Reject candidates from old generation

---

track_local_static_test.go

Fix flaky test, by adding a grace timestamp

Fix flaky test, by adding a grace timestamp

---

mediaengine.go
mediaengine_test.go

The `RegisterCodec` function is public and takes the mimeType as a string. Therefore, it should compare values using strings.EqualFold.
In general, MIME type comparisons should be done in a case-insensitive manner.
Fixes #...

Fix MIME type comparisons to be case-insensitive

---

certificate.go
certificate_js_test.go
configuration_js.go

(partially) Fixes https://github.com/libp2p/go-libp2p/issues/3277
Go WASM interop supports x509, PEM and other cryptography functions (but not all), so there is no reason not to include those in the wasm build.
This will also fix compilation errors for when something is using webrtc and targets both wasm and server
The PR was tested locally (via a simple web folder with wasm_exec.js and index.html) and I confirmed being able to generate a X509 certificate

make certificate.go partially available on wasm

---

peerconnection.go

This PR adds a space between `WMS` and `*`.
Fixes #3128

Use space after WMS. Fixes #3128

---

peerconnection.go
sdp.go
sdp_test.go

Fix trackDetailsFromSDP not handling fec ssrc

---

examples/whip-whep/index.html
examples/whip-whep/main.go

WHIP-WHEP example improvements:
- Add audio support
- Remove redundant logging from dumping SenderReport RTCP packets
- Add OPTIONS method handling for CORS to WHIP and WHEP http handlers
- Configure WHEP the same way as WHIP, using a `MediaEngine`
- Enable TWCC SEQ number sender for WHEP
Fixes https://github.com/pion/webrtc/issues/3179

WHIP-WHEP example improvements

---

constants.go
rtpreceiver.go

Notify to use ReadSimulcast with rid when multiple tracks are present in RTPReceiver
Note: The end-user is using `receiver.ReadRTCP()` instead of `receiver.ReadSimulcastRTCP(track.RID())` for handling simulcast.
The simulcast is configured with three encodings:
```
{ rid: '360', scaleResolutionDownBy: 3.0, maxBitrate: 150_000 },
{ rid: '640', scaleResolutionDownBy: 2.0, maxBitrate: 400_000 },
{ rid: '1024', scaleResolutionDownBy: 1.0, maxBitrate: 1_000_000 }
```
When the ontrack event is fired in the expected order — for example: 360 -> 640 -> 1024 
Everything seems working fine. No panic occurs, and RTCP packets are read successfully for all simulcast tracks.
RTCP is read three times, but internally, all reads point to track[0] (RID 360). 
So while it seems like RTCP is being read for …

Improve RTCP Read

---

examples/README.md
examples/ice-proxy/README.md
examples/ice-proxy/answer.go
examples/ice-proxy/main.go
examples/ice-proxy/offer.go
examples/ice-proxy/proxy.go
examples/ice-proxy/turn.go
go.mod

This PR introduces an example demonstrating how to configure and use a proxy with ICE.

Add ice-proxy example

---

rtpcodec.go
rtpcodec_test.go
rtptransceiver.go

While adding transceivers from SetRemoteDescription, the filtered codecs could filter out the primart codec and leave the RTX codec in. Generating an answer with that fails `SetRemoteDescription` on remote peer due to an unrecognisable codec. Fix it by filtering out RTX is primary is not there.

Remove RTX codec if no primary

---

peerconnection.go
peerconnection_go_test.go

When a recvonly transceiver is created from remote offer, skip partial matched codec will cause the
receiver can't be reused to send the codec.
Fixes #...

Add partialMatch codecs to transceiver from remote

---

rtpcodec.go
rtptransceiver.go
rtptransceiver_test.go

Recently added filtering out unattached RTX in SetCodecPrefrences. Turns out it is needed in `getCodecs()` also in the following scenario
- AddTrack from answer side adds a tracks and has media engine codecs
- An offer is received and negotiated codecs get updated in media engine. And this does not have one of the codecs added AddTrack above (default media engine codecs).
- Generate answer will do `getCodecs` which will filter out the codec missing from the `offer`, but would have let the corresponding RTX pass through and get added to the answer.

Filter unattached RTX when getting codecs

---

mediaengine.go
peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
rtptransceiver.go

Done when creating a transceiver from remote description to respect codec order preference of remote peer.
There was a recent change to include partial matches which overwrote same codecs and also rtx was getting magled.
Change it by removing codecs from search space as matches are found so that a codec match is applied only once.
Also, move RTX matching to separate block to ensure proper RTXes ar matched.

Match codec order of remote peer

---

interceptor.go
interceptor_test.go
peerconnection.go

Cleanup statsGetter after peer is closed to prevent memory leaks.

Cleanup statsGetter after peer is closed

---

rtpreceiver.go
rtpreceiver_test.go
stats_go.go
stats_go_test.go
track_remote.go
track_remote_test.go

- Refactored AudioPlayoutStatsProvider to provider-centric API with AddTrack/RemoveTrack methods, enabling multi-device and multi-track scenarios
- Provider represents a playout device (playout-id); tracks register to providers and stats are automatically collected via pc.GetStats()
```go
// Create provider for a playback device
provider := webrtc.NewAudioPlayoutStatsProvider("speaker-device-1")
// Register tracks with the provider
provider.AddTrack(remoteTrack)
// Inside playback callback
provider.Accumulate(frames*channels, sampleRate, deviceDelay, synthesized)
// Switch devices 
provider.RemoveTrack(remoteTrack)
headphoneProvider.AddTrack(remoteTrack)
// Stats collection via GetStats
for id, stat := range pc.GetStats() {
if playout, ok := stat.(webrtc.AudioPlayoutStats); ok {
// …
```

Add AudioPlayoutStatsProvider interface for getting media-playout stats
