.gitignore
README.md

Super tiny change. Just wanted to add just a tiny changes to gitignore so that people like me that work with jetbrains IDE do not have to suffer. :smile:

.gitignore improvement

---

internal/sdp/util.go
rtcconfiguration.go
rtcpeerconnection.go
signaling.go

This is for #53 
This is the status of examples

[WIP] FireFox support

---

.golangci.yml
README.md
errors.go
internal/dtls/dtls.go
internal/network/manager.go
internal/network/port-receive.go
internal/network/port-send.go
internal/sctp/association.go
internal/sctp/chunk.go
internal/sctp/chunk_init_common.go
internal/sdp/marshal.go
internal/sdp/media_description.go
internal/sdp/time_description.go
internal/srtp/srtp.go
media.go
mediaengine.go
pkg/ice/address.go
pkg/ice/ice.go
rtcconfiguration.go
rtcpeerconnection.go
signaling.go

fix some code by golangci linter

fix golangci linter

---

README.md
internal/sctp/chunk_payload_data.go

Fix for issue https://github.com/pions/webrtc/issues/84

Fix PayloadTypeWebRTCBinary value

---

examples/gstreamer-send/gst/gst.go
examples/save-to-disk/main.go
media.go
pkg/media/ivfwriter/ivf-writer.go
pkg/media/media.go
pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go
rtcpeerconnection.go

Move IVFWriter to `pkg` and implement `SampleBuilder` with tests

---

README.md
pkg/rtcp/packet.go
pkg/rtcp/packet_test.go

More to come. Let me know if there's anything I need to change otherwise I'll proceed with the rest of the packet types.

Start RTCP package: add header parsing

---

.github/lint-disallowed-functions-in-library.sh
pkg/rtcp/packet_test.go
rtccertificate.go
rtcpeerconnection.go
rtcpeerconnection_test.go

Don't allow panics in library code, pion-WebRTC should never
cause a user's application to exit
Resolves #125

Remove panics and fix lint

---

internal/network/manager.go

PortsManager + IceAgent are both protected by a mutex, and they both
have the ability to call and lock on other.
In a reproducible deadlock the IceAgent would send a message via the
ports manager, and at the same time the portsManager was attempting to
query the IceAgent for valid candidates.
This is fixed by moving the portsManager to a ReadLock. The places where
we lock don't have this interaction
Resolves #78, Resolves #108

Fix portsManager/IceAgent deadlock

---

pkg/ice/agent.go

IceAgent improperly returns XorAddress when finding ports.
This would cause the portManager to fail finding the relevant port
since we are bound on the local (and not our public XorAddress)
Resolves #140

Fix IceAgent improperly returning XorAddress

---

.codacy.yaml
examples/README.md
examples/example.html
examples/examples.go
examples/examples.json
examples/index.html

We can make it look fabulous down the line. I'm going for integration testing first.
Resolves #120

Examples: host examples locally

---

internal/srtp/srtp_test.go

Increase test coverage of SRTP package, add tests that assert we
can encrypt/decrypt multiple RTP packets
Resolves #118

Add full SRTP Lifecycle tests

---

pkg/ice/agent.go
rtcpeerconnection.go

ICE: Cleanup agent notifier

---

examples/examples.go

Examples: close examples.json reader

---

internal/dtls/dtls.c
internal/dtls/dtls.go
internal/dtls/dtls.h
internal/network/manager.go

- DTSL can now notify upper layers of its connection status.
Relates to #159

DTLS: Notifier & Initialization

---

internal/network/manager.go
internal/sctp/association.go
internal/sctp/chunk.go
internal/sctp/chunk_abort.go
internal/sctp/chunk_cookie_ack.go
internal/sctp/chunk_init.go
internal/sctp/chunk_init_ack.go
internal/sctp/chunk_init_common.go
internal/sctp/chunk_payload_data.go
internal/sctp/chunk_selective_ack.go
internal/sctp/error_cause.go
internal/sctp/error_cause_header.go
internal/sctp/error_cause_invalid_mandatory_parameter.go
internal/sctp/error_cause_protocol_violation.go
internal/sctp/error_cause_unrecognized_chunk_type.go
internal/sctp/packet.go
internal/sctp/param_header.go
internal/sctp/param_state_cookie.go
internal/sctp/payload_queue.go

- SCTP can now initiate a connection.
- SCTP can now notify the upper layers of its connection state.
Relates to #159

SCTP: Notifier & Initialization

---

examples/data-channels-create/main.go
examples/data-channels/main.go
examples/pion-to-pion/answer/main.go
internal/network/manager.go
internal/network/network.go
rtcdatachannel.go
rtcpeerconnection.go

- OpenChannel messages are now sent after SCTP is Established.
- The OnOpen handler tells the application when a channel has opened.
Relates to #159

DataChannels: OpenChannel & OnOpen

---

pkg/ice/agent.go

libnice is discarding our keepalives without them
Resolves #178

Add MessageIntegrity + Username in ICE keepalive

---

examples/janus-gateway/streaming/main.go

Emit `keepAlive` in Janus example

---

examples/examples.json
examples/pion-to-pion/README.md
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go

Examples: make pion-to-pion cross platform

---

internal/network/manager.go
internal/network/port-send.go
internal/stun/stun.go
pkg/ice/agent.go
pkg/ice/candidate.go
pkg/ice/url.go

Removed the iceOutboundHandler to slowly start working
towards refactoring the transports.
Relates to #195

ICE: Fix ICE not sending via reflective candidates.

---

examples/gstreamer-send-offer/gst/gst.c

Fix build breakage in example

---

rtcpeerconnection.go
rtcsignalingstate.go
rtcsignalingstate_test.go

Still a WIP, submitting for early feedback. This should provide a better foundation for implementing renegotiation support.

Signaling state

---

internal/network/port-receive.go
internal/network/port_test.go

Make sure any extra packets packed into an
encrypted payload are properly handled
Resolves #249

Handle compound SRTCP messages

---

internal/network/srtp.go
pkg/rtcp/goodbye.go
pkg/rtcp/header.go
pkg/rtcp/packet.go
pkg/rtcp/picture_loss_indication.go
pkg/rtcp/rapid_resynchronization_request.go
pkg/rtcp/raw_packet.go
pkg/rtcp/raw_packet_test.go
pkg/rtcp/reader_test.go
pkg/rtcp/receiver_report.go
pkg/rtcp/receiver_report_test.go
pkg/rtcp/reception_report.go
pkg/rtcp/sender_report.go
pkg/rtcp/slice_loss_indication.go
pkg/rtcp/slice_loss_indication_test.go
pkg/rtcp/source_description.go
pkg/rtcp/transport_layer_nack.go
pkg/rtcp/transport_layer_nack_test.go
pkg/rtp/packet.go

This also avoids a type switch in srtp.go (which may be a bit faster)
I've also added some String() members to aid in debugging
Sorry for the big commit, i can break it up if you guys want that.

Support Extra RTCP messages

---

.github/assert-contributors.sh
.github/hooks/commit-msg.sh
.github/hooks/pre-commit.sh
.github/hooks/pre-push.sh
.github/install-hooks.sh
.github/lint-commit-message.sh

* Make commit message linter less annoying
* Add git hooks to auto-run lint scripts before commit and push

Linter Updates

---

internal/sdp/ice.go
pkg/ice/agent.go
pkg/ice/candidate.go
pkg/ice/networktype.go
pkg/ice/transport_test.go
pkg/ice/util.go

This PR aims to add IPv6 support.
Sadly this also makes me run into terminal input length issues more often. We'll probably have to start compressing the SDP on the JS side.
TODO:
Resolves #85, #199

[WIP] Add IPv6 Support

---

examples/data-channels-create/README.md
examples/data-channels-create/jsfiddle/demo.js

Update data-channels-create example to use STUN

---

examples/README.md
examples/data-channels-create/README.md
examples/data-channels-create/jsfiddle/demo.js
examples/data-channels-create/main.go
examples/data-channels/README.md
examples/data-channels/jsfiddle/demo.js
examples/data-channels/main.go
examples/gstreamer-receive/README.md
examples/gstreamer-receive/jsfiddle/demo.js
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/README.md
examples/gstreamer-send/jsfiddle/demo.js
examples/gstreamer-send/main.go
examples/save-to-disk/README.md
examples/save-to-disk/jsfiddle/demo.js
examples/save-to-disk/main.go
examples/sfu/README.md
examples/sfu/jsfiddle/demo.js
examples/sfu/main.go
examples/util/util.go

Resolves #39 
TODO:
Can someone test these last two examples? I'm having trouble running them on Windows.

Examples: exchange entire RTCSessionDescription

---

README.md
mediaengine.go
pkg/rtp/codecs/g722_packet.go
pkg/rtp/codecs/g722_packet_test.go

Add a G722 RTP payloader

---

internal/sctp/association.go

SCTP: Support simultaneous open

---

examples/gstreamer-send-offer/main.go
examples/gstreamer-send/README.md
examples/gstreamer-send/main.go
examples/janus-gateway/video-room/main.go
examples/util/gstreamer-src/gst.go

This allows us to give better examples with webcam + file input
Relates to #206 #209

Extend gstreamer-src so src is an argument

---

.gitignore
.travis.yml

Our tests aren't being executed recursively, use this so everything gets run
Resolves #320

Use -coverpkg with `go test`

---

internal/network/manager.go
pkg/ice/agent.go
pkg/ice/transport_test.go
rtcicecandidate.go
rtcicecandidatetype.go
rtcicecandidatetype_test.go
rtcicegatherer.go
rtcicegatherer_test.go
rtciceprotocol.go
rtciceprotocol_test.go
rtcicetransport.go
rtcicetransportstate.go
rtcpeerconnection.go

This PR backs the PeerConnection by RTCIceGatherer and RTCIceTransport
TODO:
- ~[ ] Improve coverage RTCIceGatherer~ Will make separate PRs after the DTLS transport.
- ~[ ] Improve coverage RTCIceTransport~ Will make separate PRs after the DTLS transport.

[WIP] ORTC: ICE Gatherer and Transport

---

internal/network/manager.go
rtcdatachannel.go
rtcdtlstransport.go
rtcicetransport.go
rtcpeerconnection.go

ORTC: Back WebRTC by RTCDtlsTransport

---

examples/ortc-quic/main.go
pkg/quic/bidirectionalstream.go
pkg/quic/internal/wrapper/fakepacketconn.go
pkg/quic/internal/wrapper/listener.go
pkg/quic/internal/wrapper/quic.go
pkg/quic/internal/wrapper/stream.go
pkg/quic/streamreadresult.go
pkg/quic/streamwriteparameters.go
pkg/quic/transport.go
pkg/quic/transportbase.go
rtcquicparameters.go
rtcquicrole.go
rtcquictransport.go

 ORTC: Add RTCQuicTransport

---

internal/mux/mux_test.go
internal/network/manager.go
pkg/ice/agent.go
pkg/ice/transport_test.go
rtcpeerconnection.go
settingengine.go

Add settingEngine hooks to modify ICE timeouts

---

pkg/ice/agent.go
pkg/logging/leveled.go

Just fixing a couple of things that I wish I'd gotten into the original PR.

Logging tweaks

---

pkg/ice/agent.go

Adjust more ICE logging messages to be at Trace level.
Refers to #361

Logging cleanup

---

rtcdatachannel.go

This needed to be public when the API wasn't thread safe, this was fixed
so making member private.
Resolves #311

Make RTCDataChannel mutex private

---

.github/assert-contributors.sh
examples/data-channels-close/jsfiddle/demo.js
examples/gstreamer-receive/jsfiddle/demo.js
examples/gstreamer-send/jsfiddle/demo.js
examples/save-to-disk/jsfiddle/demo.js
examples/sfu/jsfiddle/demo.js
examples/util/gstreamer-sink/gst.c
examples/util/gstreamer-src/gst.c

Run standardjs across all js files, fix all other issues by hand

Fix Codacy warnings

---

examples/util/gstreamer-src/gst.go

The PR tackled the problem of "what happens to `gstreamer-src.Pipeline` when `pipeline.in` isn't being consumed?"
This problem would manifest itself with `pipeline.Stop()` hanging because the appsink element was hanging waiting for `pipeline.in <- media.RTCSample{}` to run.

gstreamer-src.Stop() cancels sends

---

examples/sfu/main.go

Check error when tcp port is used.

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

SampleBuilder now respects maxLate after a buffer have been popped

Fix SampleBuilder not respecting maxLate

---

rtcpeerconnection.go

This breaks the public API, but there is no reason a user should ever
have to hold on to this.

Make RTCPeerConnection lock private

---

.golangci.yml
.travis.yml
README.md
datachannel_test.go
dtlstransport.go
errors.go
icecandidate.go
icecandidatetype.go
icegatherer.go
icetransport.go
internal/mux/endpoint.go
peerconnection.go
pkg/ice/agent.go
pkg/ice/transport.go
pkg/ice/transport_test.go
quictransport.go
signalingstate.go

I rebased @wwatson PR and updated the linter

Enable gocritic and update golangci-lint version

---

go.mod
go.sum

SCTP: Bump

---

api.go
examples/gstreamer-receive/main.go
examples/gstreamer-send-offer/main.go
examples/gstreamer-send/main.go
examples/janus-gateway/streaming/main.go
examples/janus-gateway/video-room/main.go
examples/save-to-disk/main.go
examples/sfu/main.go
peerconnection.go

Relates to #434
I'll leave this open for feedback a little while longer.

Avoid defaultAPI

---

peerconnection.go
rtpreceiver.go
rtpsender.go

Move RTPSender and RTPReceiver to API

---

go.mod
go.sum
peerconnection.go

Bump pions/sdp to v2.1.0

---

README.md
peerconnection.go
rtpsender.go
rtptransceiver.go

Check that RTPTransceiver has .Sender on PeerConnection.AddTrack

---

datachannel.go
datachannel_ortc_test.go
dtlstransport.go
go.mod
internal/ice/agent.go
internal/ice/errors.go
internal/ice/url_test.go
internal/util/util.go
peerconnection.go
quictransport_test.go
rtptransceiver.go
signalingstate.go

Lots of people are paying attention to what dependecies we add to their
projects now. This just makes things a little cleaner.
Resolves #469

Remove pkg/errors dependency

---

peerconnection.go

Relates to #476; also check for a nil Receiver on the
RTPTransceiver.

Check for nil Receiver in PeerConnection.AddTrack

---

.gitignore
README.md
constants.go
datachannel.go
datachannel_js.go
datachannelmessage.go
dtlstransport.go
examples/data-channels/jsfiddle/main.go
icetransport.go
js_utils.go
peerconnection.go
peerconnection_js.go
quictransport.go
rtpreceiver.go
rtpsender.go
rtptransceiver.go
sctptransport.go
track.go

This is a very WIP PR to add WASM support. The goal is to have an isomorphic API that will work in the browser or in standalone executables. This will be implemented by using build tags and the `syscall/js` package.

Add JavaScript/WASM bindings

---

README.md
examples/README.md

WASM: Document WASM support

---

icetransport_test.go
peerconnection_media_test.go

Move ICETransport specific test to proper file, add a comment to
integration test explaining purpose

Minor test re-organization

---

peerconnection.go
peerconnection_media_test.go
rtpreceiver.go
rtpsender.go
track.go
track_test.go

Using this enum allows people to more gracefully handle shutdown errors
Resolves #511

Return io.EOF when reading/writing media

---

peerconnection.go
peerconnection_go_test.go

Don't allow answer without RemoteDescription

---

datachannel.go
sctptransport.go

Replace direct instantiation. Replace some print lines too.

Use newDataChannel in sctp transport

---

peerconnection.go
sctptransport.go

Make SCTPTransport thread safe

---

datachannel_js.go

- Added SetBufferedAmountLowThreshold
- Added OnBufferedAmountLow
Fixes #591

Updated wasm DataChannel

---

go.mod
go.sum
rtpreceiver.go
rtpsender.go

Upgrade pion/rtcp to v1.1.5

---

peerconnection.go

When generating responses we were incorrectly using numeric mid values.
This works for Unified Plan offers, but was breaking Plan-B

Responses now use the same mid values as the offer

---

README.md

Update README with some contributions

---

go.mod
go.sum
icecandidate.go

Fix candidates being able to create prflx candidates
without a full request/response cycle

Bump pion/ice

---

datachannel.go

When channel is being torn down we unset the association,
at the same time others may be accessing it. Found with
-race in travis-ci

Fix race in SCTP teardown

---

README.md
datachannel.go
datachannel_test.go
peerconnection.go

fixed create data channel returning with "SCTP not establisched"

---

peerconnection.go
peerconnection_media_test.go

Before we incorrectly created a Sendonly transceiver

Create SendRecv Transceiver when AddTrack is called

---

peerconnection.go
peerconnection_media_test.go

Populate the Label/ID for incoming tracks. Before we
emitted them to the user with empty values
Resolves #670

Populate incoming Label/ID

---

datachannel.go
datachannel_test.go

I'm not 100% sure we need the onceMutex, I believe so just because we could have a race condition between the once invokation and a new session (in which the once is instantiated again). Furthermore we cannot use the global mutex since we need to unlock it during the openHandler execution

Fix DC open handler been called twice

---

icegatherer.go
icegatheroptions.go
icetransportpolicy.go
icetransportpolicy_test.go
peerconnection.go

Add support for ICETransportPolicy and ICEGatherPolicy for ORTC

Support ICETransportPolicy

---

ice_go.go
ice_go_test.go
icecandidate.go
icecandidate_test.go
icecandidatetype.go
icecandidatetype_test.go
iceconnectionstate.go
iceconnectionstate_test.go
icegatherer.go
icegatherer_test.go
icegatheringstate.go
icegatheringstate_test.go
iceprotocol.go
iceprotocol_test.go
iceserver.go
iceserver_test.go
icetransportpolicy.go
icetransportpolicy_test.go
peerconnection.go
peerconnection_js.go
test-wasm/go_js_wasm_exec

Removed SDP dependency from ice files. Exported string to ice enum
functions. Exported ICEServer.Validate.
Rel #645

Prepare for internal/ice package

---

ice_go.go
internal/ice/gatherer.go
internal/ice/gatherer_test.go
internal/ice/transport.go
peerconnection.go
peerconnection_test.go
settingengine.go

Fix race issue caused by multiple gathering

---

settingengine.go

ICE timeout options were added but not exposed

Add missing SettingEngine setters

---

examples/data-channels-close/jsfiddle/demo.details
examples/data-channels-close/main.go
examples/data-channels-create/README.md
examples/data-channels-create/jsfiddle/demo.details
examples/data-channels-create/main.go
examples/data-channels-detach-create/main.go
examples/data-channels-detach/jsfiddle/main.go
examples/data-channels-detach/main.go
examples/data-channels/README.md
examples/data-channels/jsfiddle/demo.details
examples/data-channels/main.go
examples/echo/README.md
examples/echo/main.go
examples/ortc-quic/main.go
examples/ortc/main.go
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go
examples/save-to-disk/README.md
examples/save-to-disk/jsfiddle/demo.details
examples/save-to-disk/main.go
examples/sfu-minimal/README.md
examples/sfu-minimal/main.go
mediaengine.go

Mass rename everywhere we forgot to update

pion-webrtc -> Pion WebRTC

---

datachannel.go

Datachannel can be have a nil datachannel pointer

Fix datachannel stats invalid pointer

---

.golangci.yml
dtlstransport.go
examples/sfu-minimal/main.go
icegatherer.go
internal/mux/muxfunc.go
networktype.go
peerconnection_go_test.go
pkg/media/rtpdump/reader.go
pkg/media/rtpdump/reader_test.go
pkg/media/samplebuilder/samplebuilder_test.go

Enable gochecknoglobals linter

---

.travis.yml
examples/README.md
examples/custom-logger/README.md
examples/custom-logger/main.go
examples/examples.json
icecandidate_test.go
peerconnection.go
peerconnection_go_test.go

Demonstrate how users can user their own logger via the
SettingEngine
Resolves #726

Add custom-logger example

---

examples/data-channels-close/main.go
examples/data-channels/main.go

Panic on the actual error we are checking in
data-channels-close and data-channels

Fix examples error handling

---

go.mod
go.sum

Update pion/ice to v0.5.3
Relates to pion/ice#75

Update pion/ice to v0.5.3

---

datachannel.go
peerconnection.go
peerconnection_close_test.go
peerconnection_go_test.go
rtptransceiver.go

Eventually this will be added to golangci-lint, but for now
we have to do it manually
Relates to #106

Add godox to .travis.yml

---

README.md
peerconnection.go
peerconnection_media_test.go

This allows to have send only tracks

Implemented AddSender method on PeerConnection

---

go.mod
go.sum

Start candidate before adding it to the checklist

Bump ice to v0.5.8

---

examples/README.md
examples/echo/main.go
examples/examples.json
examples/play-from-disk/README.md
examples/play-from-disk/jsfiddle/demo.css
examples/play-from-disk/jsfiddle/demo.details
examples/play-from-disk/jsfiddle/demo.html
examples/play-from-disk/jsfiddle/demo.js
examples/play-from-disk/main.go
mediaengine.go
peerconnection.go
pkg/media/ivfreader/ivfreader.go
pkg/media/ivfreader/ivfreader_test.go

Using IVFReader demonstrate how user can play videos from hard disk to browser

Add examples/play-from-disk

---

peerconnection.go

Fixes https://github.com/pion/webrtc/issues/686
Tested on FF and chrome

Offer sdp sends setup=actpass

---

go.mod
go.sum

Small optimization to avoid unneeded string formatting

Bump sctp to 1.6.6

---

go.mod
go.sum

Bump ice to 0.5.10

---

.travis.yml
go.mod
go.sum

We are hitting 32bit specific errors for things like atomics.
This adds another step that runs our test suite via a 32bit Docker
image.
Resolves #750

Add testing for 32-bit OS

---

README.md
pkg/media/ivfwriter/ivfwriter.go
pkg/media/ivfwriter/ivfwriter_test.go

Update IVF Writer frame count when possible

---

examples/data-channels-flow-control/README.md
examples/data-channels-flow-control/main.go

Added examples/data-channels-flow-control

---

.travis.yml
datachannel_js.go
js_utils.go

Update travis to work with golang1.13 + update wasm code

Golang1.13

---

peerconnection.go

Combine two functions that always call each other

Remove indirection when setting ICEConnectionState

---

atomicbool.go
datachannel.go
dtlstransport.go
peerconnection.go
peerconnection_go_test.go
peerconnection_js.go
peerconnection_test.go

Start properly setting the PeerConnectionState and make
OnConnectionState available
Resolves #614
----
TODO

Add PeerConnectionState

---

peerconnection_media_test.go

TestSRTPDrainLeak asserts that we notify the user
of SRTP/SRTCP packets that can't be handled. Before
we tested by sending 5 packets, and looking for a log
message. If these 5 packets were lost the test would fail.
Now we send packets in a loop until they are seen.
Resolves #823
Fixes #...

Improve TestSRTPDrainLeak

---

icegatherer.go

Forgotten LOCs in https://github.com/pion/webrtc/pull/845

Honor nat 1to1 config when creating agent

---

README.md
datachannel.go
datachannel_go_test.go
dtlsrole.go
dtlstransport.go
dtlstransportstate.go
examples/data-channels-flow-control/README.md
icecandidatetype.go
icegatherer.go
peerconnection.go
peerconnection_go_test.go
peerconnection_js.go
peerconnection_media_test.go
pkg/media/oggwriter/oggwriter.go
pkg/media/rtpdump/reader_test.go
sctptransport.go
stats.go

last one... I promise :), scrubbed through the rest of the repo for discrepancies that stood out.

Various spell fixes for error types, vars, docs and comments

---

dtlsrole.go
dtlsrole_test.go
dtlstransport.go
go.sum
peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
settingengine.go
settingengine_test.go

Run DTLS as Passive instead of Active when answering

Switch DTLS default role when answering

---

dtlstransport.go
peerconnection.go
sctptransport.go

PeerConnection.Close() doesn't match the W3C RFC on closing,
re-order the transports so that they close in the proper order.
In the future we will use the DTLS Close alert and RTCP Bye to
better communicate shutdown
----
I just threw recently active people on the review, no worries if you don't have the bandwidth! I am fixing issues to help with using `croc`

Match W3C when closing

---

README.md
examples/README.md

No issue for it but happy to create one if required.

Example documentation improvements

---

examples/vnet/README.md
examples/vnet/show-network-usage/main.go
icegatherer.go
peerconnection.go
settingengine.go

Also add simple example to show usage
Resolves #778

Add vnet to SettingEngine

---

datachannel_go_test.go

When using `DetachDataChannels`, the user should `Detach` the channel
inside the `OnOpen` method. Our own test case should use the same
approach to avoid confusion.

Rewrite datachannel detach test to use Detach in OnOpen

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

`SampleBuilder.PopWithTimestamp` function is added to provide RTP timestamp of the sample.
This makes it possible to detect frame drops in user application.

Add SampleBuilder.PopWithTimestamp

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Fix overflow and underflow handling.

Fix seqnum distance in SampleBuilder

---

codecov.yml

- Rename config file since .codecov.yml is ignored on codecov server.
- Remove unused field.
related: #944

Fix codecov config

---

mediaengine.go
peerconnection.go
rtcpfeedback.go

Sdp support transport-cc
Fixes #...

Sdp support transport-cc

---

.golangci.yml
.travis.yml
dtlstransport_test.go
examples/vnet/show-network-usage/main.go
internal/mux/mux.go
internal/util/util.go
mediaengine_test.go
peerconnection.go
peerconnection_media_test.go
pkg/media/ivfreader/ivfreader.go
pkg/media/ivfwriter/ivfwriter.go
pkg/media/media.go
pkg/media/oggwriter/oggwriter.go
pkg/media/samplebuilder/samplebuilder.go

Fix whitespace and stylecheck errors.
Disable godox.
preparing https://github.com/pion/.goassets/pull/4

Upgrade golangci-lint to 1.19.1

---

mediaengine.go

Prefer Opus over G711

---

icegatherer.go
stats_go_test.go

Fix crash when GetStats called on Closed PeerConnection
Resolves #1005

Fix GetStats SEGV

---

.github/workflows/browser-e2e.yaml

Run E2E test on master branch

---

README.md

Fix pions to pion. Switch to use pkg.go.dev.
#1009

Update GoDoc link

---

e2e/e2e_test.go
e2e/test.html

Ping-pong between pion and browser.

Add e2e DataChannel test

---

peerconnection.go

Fix race in PeerConnection.setDescription

---

peerconnection_go_test.go

Add E2E Trickle ICE Test

---

errors.go
peerconnection.go
sdp.go
sdp_test.go

Move this stuff out of SetRemoteDescription so it will be easier to test
Relates to #1023

Split ICE and DTLS related SDP parsing out

---

peerconnection_go_test.go

Don't add ICECandidate before SetRemoteDescription

---

README.md
icegatherer.go
peerconnection.go

Follow up to #1051.
Fixes #1051, may also see #1052.

Adding documentation about OnICECandidate

---

README.md
examples/play-from-disk-renegotation/README.md

Super small change, fixes one 404 link.

Fix 404 link

---

README.md
examples/README.md
examples/examples.json
examples/rtp-forwarder/README.md
examples/rtp-forwarder/jsfiddle/demo.css
examples/rtp-forwarder/jsfiddle/demo.details
examples/rtp-forwarder/jsfiddle/demo.html
examples/rtp-forwarder/jsfiddle/demo.js
examples/rtp-forwarder/main.go
examples/rtp-forwarder/rtp-forwarder.sdp

Added examples/rtp-forwarder

---

peerconnection.go
peerconnection_renegotation_test.go
peerconnection_test.go

On all subsequent re-offers make sure to order
of media sections.
Add TestPeerConnection_RoleSwitch to assert this behavior
Resolves #1058

Handle changing role during re-negotiation

---

peerconnection.go

As the order of function execution of multiple goroutine is not
guaranteed, startRenegotation could be called before startTransports.
Fixes #1074

Guarantee order of startRenegotation

---

internal/util/util.go
internal/util/util_test.go

Make FlattenErrs result comparable

---

peerconnection_go_test.go

Requires pion/ice#168 to pass the test.

Add a test to check OnICECandidate order

---

README.md
peerconnection.go
peerconnection_renegotation_test.go
sdp.go
sdp_test.go

Track id label fixes

---

README.md
peerconnection.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotation_test.go
rtptransceiver.go

@Sean-Der - just wanted to share this before I call it a night. I'm not sure if you had other plans regarding issue #1148, so I'd love to hear your thoughts.
(Hopefully) Fixes #1148

Add RTPTransceiver.Mid()

---

peerconnection_renegotation_test.go

Fixes #1176. I was unable to reproduce this locally, but this must have happened because `onTrackChan` was being written to before `onTrackCount` variable was updated. I changed the order and removed the unnecessary mutex.

Fix test Renegotiation_AddTrack_Multiple

---

peerconnection_media_test.go
peerconnection_renegotation_test.go

Fix hanging test Transceiver_Mid

---

constants.go
peerconnection.go
peerconnection_renegotiation_test.go
sdp.go
sdp_test.go

Only start SCTP if RemoteDescription requests

---

peerconnection.go
peerconnection_media_test.go

We had an off-by-one when generating PlanB offers. Fix and add a test

Fix single track PlanB offers

---

pkg/media/samplebuilder/samplebuilder.go

There's one more piece I want to document, but I need some input.
What is the intended usage pattern? The obvious one is:
```go
// create SampleBuilder sb
for  {
//  get packet p
sb.Push(p)
sample := sb.Pop()
if sample == nil {
continue
}
// use sample
}
```
But it seems like it is theoretically possible for multiple samples to be available as a result of a single new packet (e.g. a single packet was missing a long time and then shows up). So maybe correct use is like this?
```go
// create SampleBuilder sb
for  {
//  get packet p
sb.Push(p)
for {
sample := sb.Pop()
if sample == nil {
break
}
// use sample
}
}
```
If you advise, I will document.
Also, I think the docs would benefit from mentioning typical maxLate sizes. What would you normally suggest? (Presumably different for audio and …

Overhaul the samplebuilder docs

---

errors.go
sdp.go
sdp_test.go

Also add tests to assert we don't have conflicting values. This could
have happened before but we never tested for it.

Support ICE values at session level

---

examples/README.md
examples/examples.json
examples/insertable-streams/README.md
examples/insertable-streams/jsfiddle/demo.css
examples/insertable-streams/jsfiddle/demo.details
examples/insertable-streams/jsfiddle/demo.html
examples/insertable-streams/jsfiddle/demo.js
examples/insertable-streams/main.go

Use simple XOR Cipher on both sides. In the Web UI
you can flip a checkbox and watch decoding fail when
decryption is disabled.

Example of using Insertable Streams with Pion

---

README.md
examples/play-from-disk/README.md
examples/play-from-disk/jsfiddle/demo.js
examples/play-from-disk/main.go
pkg/media/oggreader/oggreader.go
pkg/media/oggreader/oggreader_test.go

Start oggreader, this allows a user to demux an oggfile so they can
easily play files from disk.
Resolves: #1133
Co-authored-by: Somers Matthews <somersbmatthews@gmail.com>
Co-authored-by: funvit <funvit@gmail.com>

Add media/oggreader

---

mediaengine.go
mediaengine_test.go

added method for getting codecs by name;
It's mostly useful when we going to receive offers from different browsers.

GetCodecsByName method;

---

README.md

Link to Wiki, Slack and last v2 release.

Add 'Breaking Changes' to the top of README.md

---

examples/ice-restart/README.md
examples/ice-restart/index.html
examples/ice-restart/main.go
gathering_complete_promise.go
go.mod
go.sum
icegatherer.go
icetransport.go
peerconnection.go
peerconnection_go_test.go

Resolves #1251 
@jech I added a dedicated demo page to show off the behavior, hopefully that is everything you need!

Implement ICE Restarts

---

peerconnection.go

@Sean-Der - does this fix the flakiness?
Hopefully Fixes #1290

Get a list of transceivers before starting RTP

---

go.sum

Fix go.sum.
https://github.com/pion/webrtc/pull/1306 is failing due to this.

Apply go mod tidy

---

sdpsemantics_test.go

PeerConnections were not closed.

Fix leak in TestSDPSemantics

---

peerconnection.go
peerconnection_close_test.go
peerconnection_go_test.go
peerconnection_media_test.go
peerconnection_renegotiation_test.go
peerconnection_test.go

Don't create data media sections unless we're asked to
Fixes #1349

Remove implicit data section

---

README.md
datachannel.go
datachannel_go_test.go
dtlstransport.go
gathering_complete_promise.go
icegatherer.go
icetransport.go
peerconnection.go
peerconnection_js.go
sctptransport.go

Modify hdlr to handler for better reading

---

README.md
examples/on-negotiation-needed/README.md
examples/on-negotiation-needed/index.html
examples/on-negotiation-needed/main.go
examples/on-negotiation-needed/main.js
operations.go
peerconnection.go
peerconnection_js.go
peerconnection_renegotiation_test.go
peerconnection_test.go
peerconnectionstate.go
rtptransceiverdirection.go
sdp.go
signalingstate.go
track.go

This event is fired when a change has occurred
which requires session negotiation.
Resolves #817

Implement OnNegotiationNeeded

---

peerconnection.go
rtpsender.go
sdp.go

checkNegotiationNeeded accessed RtpSender field with taking lock
Resolves #1384

Fix renegotation race

---

peerconnection.go

safely access transceivers and signaling state

fix(peerconnection): fix negotiation needed race

---

peerconnection.go

Adds a few locks to solve a few race conditions with renegotiations. This are the simplest fixes so pulled them out. Hopefully it will make them easier to land

Fix: negotiation state race conditions

---

README.md
datachannel.go
datachannel_ortc_test.go
go.sum

return io.ErrClosedPipe instead of default error coming from ensureOpened
wrote test for attempting to send when close
Fixes #...https://github.com/pion/webrtc/issues/1211

Fix issue 1211

---

certificate.go
certificate_test.go
peerconnection.go
stats_go.go
stats_go_test.go

Add an API to get basic stats around certificate
Relates to #610
Fixes #...

Add GetCertificateStats to StatsReport

---

mediaengine.go
peerconnection.go
stats.go
stats_go.go
stats_go_test.go

implemented getstats api for rpccodec
https://github.com/pion/webrtc/issues/610
Fixes #...

Implements GetStats: RTCCodecStats 

---

README.md
pkg/rtcerr/errors.go

Add Unwrap method for error types

---

peerconnection_media_test.go
track.go

Dropping a packet at the beginning of every track is bad, since
it corrupts the first keyframe of each video track.  This works
by adding a peek method to Track, and using it in NewTrack.
The peeked data is protected by the RWLock already associated
with the track.  We check for its presence with the reader lock
taken, which avoids taking the writer lock (or doing an atomic read)
in the common case (no peeked data).
Fixes #1001

Don't lose packet for OnTrack PayloadType probe

---

icetransport_test.go
peerconnection.go
peerconnection_renegotiation_test.go

This is needed so users can use OnSelectedCandidatePairChange
for DataChannel use cases.
Resolves #713

Add SCTPTransport getter to PeerConnection

---

peerconnection.go
peerconnection_renegotiation_test.go

If a remote Offer stops a mid make sure we also stop the mid locally

Handle remote offer stopping mid

---

errors.go
rtpreceiver.go

Add methods to support reading RTCP packets from simulcast tracks.

Add read rtcp from simulcast tracks methods

---

peerconnection.go

1. remove duplicate `pc.onNegotiationNeeded` calls

fix(pc): remove duplicate `pc.onNegotiatioNeeded`. throw if Sender nil for Send transceiver

---

peerconnection_js.go

Use the value of string pointer.
Fixes #1484

Fix usernameFragment string pointer to value

---

peerconnection.go

setting and calling the handler can race

fix: onnegotiationneeded handler race

---

rtptransceiver.go

This pr add public methods helpers.

Add public helper methods

---

peerconnection_renegotiation_test.go

We already have extensive tests for tracks. Update this test
to just assert that CreateDataChannel fires OnNegotiationNeeded.

Simplify TestNegotiationTrackAndChannel

---

mediaengine.go
peerconnection_go_test.go
peerconnection_renegotiation_test.go

Test still asserts that `OnNegotiationNeeded` is able to signal all
500 tracks.

Simplify TestNegotiationNeededStressOneSided

---

api.go
api_test.go
examples/ice-tcp/main.go
examples/reflect/main.go
examples/rtp-forwarder/main.go
examples/save-to-disk/main.go
peerconnection.go

These change will allow to use the MediaEngine outside Pion context
Fixes #1538

Make WithMediaEngine to receive a pointer

---

rtpsender.go
rtpsender_test.go
rtptransceiver.go
track_local.go
track_local_static.go

Implement RTPSender.ReplaceTrack

---

srtp_writer_future.go
track_local_static_test.go

A Track shouldn't block until a PeerConnection is connected. It should
only send to PeerConnections that are fully established. v3 Track API
changed this behavior by mistake.
Related to pion/transport#116

Write/WriteRTP shouldn't block before SRTP

---

pkg/media/samplebuilder/samplebuilder.go

Add float casting to time duration calculation to get correct result
Credits:
Mission liao

Fix media sample duration calculation

---

pkg/media/samplebuilder/samplebuilder.go
pkg/media/samplebuilder/samplebuilder_test.go

Add an option `samplebuilder.WithPacketReleaseHandler` to add a hook when a packets is released by `samplebuilder.SampleBuilder`. This allow us to recycle the packet buffer via `sync.Pool`.

Add option to add hook for packets released

---

peerconnection.go
peerconnection_media_test.go

pion/srtp requires that all incoming streams are accepted. You
can't close if you have unaccepted streams. At the same time storeSimulcastStream
blocks on taking the DTLSTransport lock.
Move `storeSimulcastStream` into a routine so that all streams can be accepted and
aren't blocked on taking the DTLSTransport lock.
Resolves #1586

Store Accepted Simulcast in routine

---

gathering_complete_promise.go

It's possible that the ICE gathering is completed after the execution goes to the else statement but before the setGatherCompleteHandler finishes. In other words, it's possible that the handler misses the event and block the caller forever.

Fix a race condition in GatheringCompletePromise

---

datachannel_go_test.go
sdp.go

Update from draft-ietf-mmusic-sctp-sdp

Use proper values for application media section

---

dtlstransport_test.go
peerconnection_media_test.go
rtpreceiver_test.go
rtpsender.go
rtpsender_test.go
srtp_writer_future.go

This PR aims to add SetReadDeadline to RTPSender. Please feel free to let me know if anything is missed. (And yes, I just realized that there is also a `ReadRTCP` method in `RTPSender`.

Add SetReadDeadline to RTPSender

---

dtlstransport.go
peerconnection.go

This will make possible to write RTCP using ORTC API

Add WriteRTCP method to dtls transport

---

README.md
certificate.go
certificate_test.go
errors.go

Allow for easier usage of a pre-existing certificate

Add CertificateFromPEM and PEM() to Certificate

---

README.md
peerconnection.go
peerconnection_js.go
peerconnection_media_test.go
peerconnection_test.go
rtpreceiver_js.go
rtpsender_js.go
rtptransceiver_js.go

Add AddTransceiverFromKind and GetTransceivers. This doesn't support
everything, but enough to at least build a recvonly experience.
Resolves #500

Implement WASM Media methods

---

e2e/Dockerfile
go.mod
go.sum
icegatherer.go
settingengine.go

When set, Pion will handle ICE connections over UDPMux

Introduce UDPMux in SettingsEngine, single-port

---

mediaengine.go
mediaengine_test.go

codec has apt fmtp can't negotiation because it's
apt payloadtype can't be found in negotiation codecs.
Description
codec has apt fmtp can't negotiation because it's apt payloadtype can't be found in mediaengine's negotiation codecs.
Fix
transfer exactMatch and partialMatch codec to matchRemoteCodec method, so apt payloadtype can be found in codecs.

Fixes MediaEngine: codec apt negotiation

---

errors.go
mediaengine.go
peerconnection.go
rtpreceiver.go
rtpsender.go
rtptransceiver.go
rtptransceiver_test.go
sdp.go
sdp_test.go

This allows to set supported codecs per transceiver.
Resolves #1847
----
@digitalix Instead of slowing down the review process I am just gonna take a few mins and fix up myself! Feel free to push to this branch also. Will leave notes on what I changed. If you agree when I am done go ahead and merge :)

Implements SetCodecPreferences in RTPTransceiver

---

pkg/media/samplebuilder/samplebuilder_test.go

This adds some benchmarks copied from jech/samplebuilder.
```
name                           old time/op    new time/op    delta
SampleBuilderSequential-8         313ns ± 6%     235ns ±10%  -24.93%  (p=0.029 n=4+4)
SampleBuilderLoss-8               296ns ± 6%     193ns ±11%  -34.64%  (p=0.029 n=4+4)
SampleBuilderReordered-8          338ns ± 5%     241ns ±16%  -28.66%  (p=0.029 n=4+4)
SampleBuilderFragmented-8         299ns ± 4%     230ns ±14%  -23.12%  (p=0.029 n=4+4)
SampleBuilderFragmentedLoss-8     281ns ± 5%     190ns ±19%  -32.63%  (p=0.029 n=4+4)
name                           old alloc/op   new alloc/op   delta
SampleBuilderSequential-8          336B ± 0%      336B ± 0%     ~     (all equal)
SampleBuilderLoss-8                300B ± 0%      290B ± 0%   -3.33%  (p=0.029 n=4+4) …
```

Add benchmarks from jech/samplebuilder

---

AUTHORS.txt
pkg/media/ivfwriter/ivfwriter_test.go

Split into generic and VP8 specific

Refactor IVFWriter tests

---

peerconnection.go
peerconnection_media_test.go
rtpreceiver.go
sdp.go
sdp_test.go

Implement SSRC Based Simulcast

---

peerconnection.go
peerconnection_renegotiation_test.go
sdp.go

Write tests for a Simulcast transceiver going to inactive and mid
changing

Implement Simulcast Track shutdown

---

peerconnection_media_test.go

Set custom ICE timing via SettingEngine

Reduce PeerConnection_Media_Disconnected runtime

---

peerconnection_close_test.go

Reduce PeerConnection_Close_PreICE

---

interceptor.go

This is what chrome does as well.
Fixes #...

Enabel TWCC for audio by default

---

examples/play-from-disk/README.md
examples/play-from-disk/jsfiddle/demo.html
examples/play-from-disk/jsfiddle/demo.js

It contains new "copy SDP" button

Update jsfiddle in play-from-disk

---

datachannel_test.go

5dc7245 was missing a test for this

Add test for negotiated DataChannel.OnOpen

---

datachannel.go
mediaengine.go

Two separate potential deadlocks
1. typically the locking order is SRTP first, then DataChannel. However, when data channel is opened, it's locking srtp when generating an ID. It also would return without unlocking when an error is encountered
2. recursive RLock could be potentially problematic. MediaEngine contained a section doing so.

Fixed locking order in SRTP and DataChannel

---

sctptransport.go

Take lock when getting DataChannel ID

---

examples/bandwidth-estimation-from-disk/README.md
examples/bandwidth-estimation-from-disk/main.go

Loops over three files and switches on an interval.

Start examples/bandwidth-estimation-from-disk

---

examples/bandwidth-estimation-from-disk/main.go

On startup check if video files exist

Improve bandwidth-estimation-from-disk error

---

api.go
api_test.go

mv default initialize before options;
Mv `With` options fixes into separate change;

Defaultize codestyle;

---

.github/workflows/standardjs.yaml
examples/broadcast/jsfiddle/demo.js
examples/data-channels/jsfiddle/demo.js
examples/insertable-streams/jsfiddle/demo.js
examples/reflect/jsfiddle/demo.js
examples/rtp-forwarder/jsfiddle/demo.js
examples/save-to-disk/jsfiddle/demo.js
examples/simulcast/jsfiddle/demo.js
examples/swap-tracks/jsfiddle/demo.js
test-wasm/node_shim.js

Been running these locally only.

Add StandardJS workflow

---

dtlstransport.go
settingengine.go
settingengine_test.go

Add SetDTLSRetranmissionInterval setting to SettingEngine.

DTLS retransmission interval setting

---

dtlstransport_js.go
examples/data-channels/jsfiddle/main.go
icetransport_js.go
peerconnection_js.go
peerconnection_test.go
rtpsender_test.go
sctptransport_js.go

Only available in the browser, not in wrtc yet.
Resolves #2099

Add DTLS, ICE and SCTP Transport to WASM

---

internal/mux/mux.go
internal/mux/mux_test.go

Mux will now wait and re-try writes (infinitely) when an endpoint's buffer is full.
Other code comments suggest that the buffer should never become full (see line 60 below), but that seems to not always be the case—and this is causing a race condition.
https://github.com/pion/webrtc/blob/655daa9689576421c194059dd4f3a05cae544a07/internal/mux/mux.go#L59-L62
This PR's approach may not be an ideal solution to the underlying problem, but as a band-aid it does appear to fix the issue.
This PR also updates the associated stress test to add CPU load while running, in order to trigger the bug outlined in https://github.com/pion/webrtc/issues/2152.
It's possible to verify this fix by merging only the updated test first—you'll see that quite often the test will stall with `mux ERROR: 2022/03/18 …

Mux: Wait and re-try writes (infinitely) when endpoint buffer is full

---

internal/mux/mux.go

Unlock on error in internal/mux

---

AUTHORS.txt
rtptransceiverdirection.go

Move and remove several `the` in comments.

Update several the in comments

---

peerconnection_js.go

Enable credential+credentialType for WASM

---

internal/mux/mux.go
internal/mux/mux_test.go

Removes wait-and-retry behavior in favor of dropping packets when the endpoint read buffer is full.
For SCTP, the dropped packets don't matter because they will be re-sent if necessary. I've confirmed that this is happening and that SCTP continues to recover properly.
Removing retries reverts the fix in 93b0f2a75eae5139362faf5346f0b6d53cfbf20d where tests that rely on test.StressDuplex would hang (and eventually timeout panic) if the test machine was under load, leading to a full buffer. The hang occurs because test.StressDuplex blocks until all packets are received. I've added a note about this to the relevant test. It's unlikely to be encountered.
Resolves #2180

mux: drop packets when buffer is full

---

sdp.go
sdp_test.go

Fix ice-lite attribute

---

icecredentialtype.go
icecredentialtype_test.go
iceserver.go
iceserver_test.go
peerconnection_js.go

Ensure that the zero value of ICECredentialType is password.

Fix the zero value of ICECredentialType

---

certificate_test.go
sdpsemantics_test.go
stats_go_test.go

specifically, tests for certificate.go and sdpsemantics.go

Add a few tests, to improve coverage

---

AUTHORS.txt
go.mod
go.sum

Update module github.com/pion/dtls/v2 to v2.1.5

---

mediaengine.go
mediaengine_test.go

Generate unique extmap id for extesions with different uri
fix #2235 
Fixes #...

Generate unique extmap id for extensions

---

internal/fmtp/fmtp.go
mediaengine_test.go

Relates to pion/webrtc #2241
Fixes #2241

Test for incorrect case insensitive mimetype check

---

README.md

NLnet sponsors work on congestion control in Pion.

Add reference to NLnet sponsoring

---

track_local_static.go

Nothing crazy here, I was exploring the code base and thought this would be an easy thing to refactor
Essentially I am moving some of the duplicated actions that Get/Put packet allocations from the Pool into reusable functions :)
Fixes #...

Moved duplicate operation to function

---

peerconnection.go

When PeerConnection is closed, need to call the unhandled stream's close method to release the buffer created by BufferFactory, otherwise might cause resource leak if the user provides BufferFactory need close method to release the resource.
Fixes #...

Close unhandled stream when peerconnection closed

---

settingengine.go

Fix docs typo

---

icegatherer.go
settingengine.go

Add EnableLoopbackCandidate flag to setting engine, relates to https://github.com/pion/ice/pull/497

Add EnableLoopbackCandidate flag

---

datachannel.go
datachannel_go_test.go

Adds an `OnDial` handler to be fired once the dialing side has sent the DCEP OPEN message over the data channel.
DCEP specifies that ordered data can be sent by the dialing side as soon as it has sent the open message ([link](https://www.rfc-editor.org/rfc/rfc8832.html#section-6)):
> After the DATA_CHANNEL_OPEN message has been sent, the sender of that message MAY start sending messages containing user data without waiting for the reception of the corresponding DATA_CHANNEL_ACK message. However, before the DATA_CHANNEL_ACK message or any other message has been received on a data channel, all other messages containing user data and belonging to this data channel MUST be sent ordered, no matter whether the data channel is ordered or not
Leveraging this is useful in applications that only …

Add OnDial handler for datachannels

---

go.mod
go.sum

v2.2.15 accidentally was an off branch commit.

Update module github.com/pion/ice/v2 to v2.2.16

---

AUTHORS.txt
examples/data-channels/README.md

Start new architecture section

Add Mermaid Chart to examples/data-channels

---

dtlstransport.go
settingengine.go
settingengine_test.go

Add support to configure EllipticCurves in DTLS 
https://github.com/pion/dtls/pull/474

Add SetDTLSEllipticCurves

---

dtlstransport.go
settingengine.go
settingengine_test.go

Config dtls handshake for peerconn
New request

set config for dtls handshake timeout

---

AUTHORS.txt
icegatherer.go
settingengine.go

Use SettingsEngine.DisableActiveTCP(true)
Related to https://github.com/pion/ice/pull/586

Add SettingsEngine option to disable ICE active TCP

---

pkg/media/oggwriter/oggwriter.go
pkg/media/oggwriter/oggwriter_test.go

PR adds packet segmentation capability to `OggWriter`. This makes it possible to accept payloads bigger than 255 bytes which are actually more common that I thought (e.g. Firefox seems to be generating quite a few). Without this change we'd be defaulting to a single segment causing data loss when writing and corrupted files as consequence.
There's still a theoretical limit of 255 segments per page that we are not handling (packets spanning pages) but for encoded audio data I am hoping that shouldn't ever become an issue.
Likely related to https://github.com/pion/webrtc/issues/2472

OggWriter: add packet segmentation

---

peerconnection.go
rtpcodec.go
sdp.go
sdp_test.go

Generate answer to match group bundle in offer

---

examples/custom-logger/main.go
examples/data-channels-detach/main.go
examples/data-channels-flow-control/main.go
examples/data-channels/main.go
examples/insertable-streams/main.go
examples/pion-to-pion/answer/main.go
examples/pion-to-pion/offer/main.go
examples/play-from-disk-renegotiation/main.go
examples/play-from-disk/main.go
examples/reflect/main.go
examples/rtp-forwarder/main.go
examples/save-to-disk-av1/main.go
examples/save-to-disk/main.go
examples/simulcast/main.go
examples/swap-tracks/main.go
examples/vnet/show-network-usage/main.go

Update examples to handle going to Closed

---

dtlstransport.go
settingengine.go

Add SetDTLSCustomCipherSuite to SettingEngine

---

examples/vnet/show-network-usage/main.go
peerconnection_renegotiation_test.go
rtptransceiverinit.go
settingengine.go
vnet_test.go

Delete everything that was marked as deprecated

Remove deprecated APIs

---

peerconnection_media_test.go
rtpreceiver.go

Add Simulcast RTCP Test

---

sdp_test.go

Add test for ssrc-group after ssrc

---

rtpreceiver_go_test.go

Add test for TrackRemote and RTX Packets

---

internal/fmtp/av1.go
internal/fmtp/vp9.go

As requested by @edaniels in #2772

Add links to RTP payload format specifications

---

rtpsender.go
rtpsender_test.go

Create rtcpInterceptor before bind called.
Fixes #...

Fix nil rtcpInterceptor on track.Bind

---

examples/save-to-disk-av1/README.md
examples/save-to-disk/README.md

Fix broken links in save-to-disk examples

Fix broken links in save-to-disk examples

---

icegatherer.go

Missed Done when error in collecting

Missed Done when collecting ice stats

---

pkg/media/ivfwriter/ivfwriter.go

Break the WriteRTP function into smaller functions for each codec type. For better maintainability and to remove all the nolint.

Refactor Ivfwriter.WriteRTP implemention

---

icecandidate.go
icecandidate_test.go
icetransport.go
sdp.go

Expose ToICE() method on ICE candidates to allow for easier conversion to ice package ICE candidates.
Resolve https://github.com/pion/webrtc/issues/3069

Expose ICE candidates ToICE() method

---

README.md

Update readme add discord and bluesky badges and links

Update readme add discord and bluesky

---

README.md

Add bluesky link next to twitter

Add bluesky link next to twitter

---

interceptor_test.go

I’ve occasionally experienced test failures due to timeouts in `testInterceptorNack`.  
This PR ensures that the test waits for `PeerConnection` to reach the `connected` state before sending RTP, improving test reliability.
Fixes #...

test: wait for PeerConnection to reach 'connected' in NACK test

---

peerconnection_go_test.go

If IPv6 is supported assert that Pion can connect via it.
Resolves #1315

Add IPv6 Test

---

mediaengine.go

Fix linter

---

examples/save-to-disk-av1/main.go

Remove comment, because it's av1 codec

Remove comment

---

mediaengine.go

H265 will be available by default now

Add H265 to RegisterDefaultCodecs

---

.github/.ci.conf

Remove TEST_EXTRA_ARGS and GOLANGCI_LINT_EXRA_ARGS

---

peerconnection_renegotiation_test.go
rtpsender.go

TrackEndcodings could change when reading
Fixes #...

Solve data race in ReadSimulcast

---

sctptransport.go
settingengine.go

relate: https://github.com/pion/sctp/pull/354
Fixes #...

Add methods for tweaking sctp cc to settingending

---

peerconnection_go_test.go

Per @Sean-Der 's  comments in this PR
(https://github.com/pion/webrtc/pull/3198) ([comment](https://github.com/pion/webrtc/pull/3198#issuecomment-3218234554)), adding a couple of more tests to ensure that direction in SDP is correct when remote offer is processed and transceivers are matched up against existing ones using type and direction.
Test flow
- AddTrack first on answer side. This should create a transceiver with `sendrecv`
- Receive remote description offer
- First time, it will try to match using type and direction. o If the remote offer had a media section with `sendonly`, the above should fail to find a match. In this case, a new transceiver will be created. So, there should be 2 transceivers (one from this + one from AddTrack in Step 1). In this case, the answer will have …

Tests to ensure proper direction in SDP

---

peerconnection.go
pkg/media/h264reader/h264reader.go
pkg/media/h265reader/h265reader.go
pkg/media/samplebuilder/samplebuilder_test.go
rtptransceiverdirection.go
sdp.go

Applies go modernization suggestions, see https://pkg.go.dev/golang.org/x/tools/gopls/internal/analysis/modernize for more details.
@JoeTurki and I are looking into a linting option for this, but in the meantime applying these changes should be trivial as it only makes the codebase cleaner.
N/A

Apply go modernize suggestions

---

sdp_test.go
settingengine_test.go
signalingstate_test.go
srtp_writer_future_test.go
stats.go
stats_go_test.go
track_local_static_test.go
track_test.go

Improves code coverage by adding misc. tests.
N/A

Improve code coverage

---

internal/mux/mux.go
peerconnection.go

remove `//nolint:makezero` and prefer make 0.

Prefer makezero with a cap
